// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	api "github.com/mafilus/durabletask-go/api"
	backend "github.com/mafilus/durabletask-go/backend"

	context "context"

	mock "github.com/stretchr/testify/mock"

	protos "github.com/mafilus/durabletask-go/api/protos"
)

// Backend is an autogenerated mock type for the Backend type
type Backend struct {
	mock.Mock
}

type Backend_Expecter struct {
	mock *mock.Mock
}

func (_m *Backend) EXPECT() *Backend_Expecter {
	return &Backend_Expecter{mock: &_m.Mock}
}

// AbandonActivityWorkItem provides a mock function with given fields: _a0, _a1
func (_m *Backend) AbandonActivityWorkItem(_a0 context.Context, _a1 *backend.ActivityWorkItem) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AbandonActivityWorkItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *backend.ActivityWorkItem) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Backend_AbandonActivityWorkItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AbandonActivityWorkItem'
type Backend_AbandonActivityWorkItem_Call struct {
	*mock.Call
}

// AbandonActivityWorkItem is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *backend.ActivityWorkItem
func (_e *Backend_Expecter) AbandonActivityWorkItem(_a0 interface{}, _a1 interface{}) *Backend_AbandonActivityWorkItem_Call {
	return &Backend_AbandonActivityWorkItem_Call{Call: _e.mock.On("AbandonActivityWorkItem", _a0, _a1)}
}

func (_c *Backend_AbandonActivityWorkItem_Call) Run(run func(_a0 context.Context, _a1 *backend.ActivityWorkItem)) *Backend_AbandonActivityWorkItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*backend.ActivityWorkItem))
	})
	return _c
}

func (_c *Backend_AbandonActivityWorkItem_Call) Return(_a0 error) *Backend_AbandonActivityWorkItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Backend_AbandonActivityWorkItem_Call) RunAndReturn(run func(context.Context, *backend.ActivityWorkItem) error) *Backend_AbandonActivityWorkItem_Call {
	_c.Call.Return(run)
	return _c
}

// AbandonWorkflowWorkItem provides a mock function with given fields: _a0, _a1
func (_m *Backend) AbandonWorkflowWorkItem(_a0 context.Context, _a1 *backend.WorkflowWorkItem) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AbandonWorkflowWorkItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *backend.WorkflowWorkItem) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Backend_AbandonWorkflowWorkItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AbandonWorkflowWorkItem'
type Backend_AbandonWorkflowWorkItem_Call struct {
	*mock.Call
}

// AbandonWorkflowWorkItem is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *backend.WorkflowWorkItem
func (_e *Backend_Expecter) AbandonWorkflowWorkItem(_a0 interface{}, _a1 interface{}) *Backend_AbandonWorkflowWorkItem_Call {
	return &Backend_AbandonWorkflowWorkItem_Call{Call: _e.mock.On("AbandonWorkflowWorkItem", _a0, _a1)}
}

func (_c *Backend_AbandonWorkflowWorkItem_Call) Run(run func(_a0 context.Context, _a1 *backend.WorkflowWorkItem)) *Backend_AbandonWorkflowWorkItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*backend.WorkflowWorkItem))
	})
	return _c
}

func (_c *Backend_AbandonWorkflowWorkItem_Call) Return(_a0 error) *Backend_AbandonWorkflowWorkItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Backend_AbandonWorkflowWorkItem_Call) RunAndReturn(run func(context.Context, *backend.WorkflowWorkItem) error) *Backend_AbandonWorkflowWorkItem_Call {
	_c.Call.Return(run)
	return _c
}

// AddNewWorkflowEvent provides a mock function with given fields: _a0, _a1, _a2
func (_m *Backend) AddNewWorkflowEvent(_a0 context.Context, _a1 api.InstanceID, _a2 *protos.HistoryEvent) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for AddNewWorkflowEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, api.InstanceID, *protos.HistoryEvent) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Backend_AddNewWorkflowEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddNewWorkflowEvent'
type Backend_AddNewWorkflowEvent_Call struct {
	*mock.Call
}

// AddNewWorkflowEvent is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 api.InstanceID
//   - _a2 *protos.HistoryEvent
func (_e *Backend_Expecter) AddNewWorkflowEvent(_a0 interface{}, _a1 interface{}, _a2 interface{}) *Backend_AddNewWorkflowEvent_Call {
	return &Backend_AddNewWorkflowEvent_Call{Call: _e.mock.On("AddNewWorkflowEvent", _a0, _a1, _a2)}
}

func (_c *Backend_AddNewWorkflowEvent_Call) Run(run func(_a0 context.Context, _a1 api.InstanceID, _a2 *protos.HistoryEvent)) *Backend_AddNewWorkflowEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(api.InstanceID), args[2].(*protos.HistoryEvent))
	})
	return _c
}

func (_c *Backend_AddNewWorkflowEvent_Call) Return(_a0 error) *Backend_AddNewWorkflowEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Backend_AddNewWorkflowEvent_Call) RunAndReturn(run func(context.Context, api.InstanceID, *protos.HistoryEvent) error) *Backend_AddNewWorkflowEvent_Call {
	_c.Call.Return(run)
	return _c
}

// CancelActivityTask provides a mock function with given fields: _a0, _a1, _a2
func (_m *Backend) CancelActivityTask(_a0 context.Context, _a1 api.InstanceID, _a2 int32) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for CancelActivityTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, api.InstanceID, int32) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Backend_CancelActivityTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelActivityTask'
type Backend_CancelActivityTask_Call struct {
	*mock.Call
}

// CancelActivityTask is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 api.InstanceID
//   - _a2 int32
func (_e *Backend_Expecter) CancelActivityTask(_a0 interface{}, _a1 interface{}, _a2 interface{}) *Backend_CancelActivityTask_Call {
	return &Backend_CancelActivityTask_Call{Call: _e.mock.On("CancelActivityTask", _a0, _a1, _a2)}
}

func (_c *Backend_CancelActivityTask_Call) Run(run func(_a0 context.Context, _a1 api.InstanceID, _a2 int32)) *Backend_CancelActivityTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(api.InstanceID), args[2].(int32))
	})
	return _c
}

func (_c *Backend_CancelActivityTask_Call) Return(_a0 error) *Backend_CancelActivityTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Backend_CancelActivityTask_Call) RunAndReturn(run func(context.Context, api.InstanceID, int32) error) *Backend_CancelActivityTask_Call {
	_c.Call.Return(run)
	return _c
}

// CancelWorkflowTask provides a mock function with given fields: _a0, _a1
func (_m *Backend) CancelWorkflowTask(_a0 context.Context, _a1 api.InstanceID) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CancelWorkflowTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, api.InstanceID) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Backend_CancelWorkflowTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelWorkflowTask'
type Backend_CancelWorkflowTask_Call struct {
	*mock.Call
}

// CancelWorkflowTask is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 api.InstanceID
func (_e *Backend_Expecter) CancelWorkflowTask(_a0 interface{}, _a1 interface{}) *Backend_CancelWorkflowTask_Call {
	return &Backend_CancelWorkflowTask_Call{Call: _e.mock.On("CancelWorkflowTask", _a0, _a1)}
}

func (_c *Backend_CancelWorkflowTask_Call) Run(run func(_a0 context.Context, _a1 api.InstanceID)) *Backend_CancelWorkflowTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(api.InstanceID))
	})
	return _c
}

func (_c *Backend_CancelWorkflowTask_Call) Return(_a0 error) *Backend_CancelWorkflowTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Backend_CancelWorkflowTask_Call) RunAndReturn(run func(context.Context, api.InstanceID) error) *Backend_CancelWorkflowTask_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteActivityTask provides a mock function with given fields: _a0, _a1
func (_m *Backend) CompleteActivityTask(_a0 context.Context, _a1 *protos.ActivityResponse) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CompleteActivityTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *protos.ActivityResponse) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Backend_CompleteActivityTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteActivityTask'
type Backend_CompleteActivityTask_Call struct {
	*mock.Call
}

// CompleteActivityTask is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *protos.ActivityResponse
func (_e *Backend_Expecter) CompleteActivityTask(_a0 interface{}, _a1 interface{}) *Backend_CompleteActivityTask_Call {
	return &Backend_CompleteActivityTask_Call{Call: _e.mock.On("CompleteActivityTask", _a0, _a1)}
}

func (_c *Backend_CompleteActivityTask_Call) Run(run func(_a0 context.Context, _a1 *protos.ActivityResponse)) *Backend_CompleteActivityTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*protos.ActivityResponse))
	})
	return _c
}

func (_c *Backend_CompleteActivityTask_Call) Return(_a0 error) *Backend_CompleteActivityTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Backend_CompleteActivityTask_Call) RunAndReturn(run func(context.Context, *protos.ActivityResponse) error) *Backend_CompleteActivityTask_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteActivityWorkItem provides a mock function with given fields: _a0, _a1
func (_m *Backend) CompleteActivityWorkItem(_a0 context.Context, _a1 *backend.ActivityWorkItem) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CompleteActivityWorkItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *backend.ActivityWorkItem) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Backend_CompleteActivityWorkItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteActivityWorkItem'
type Backend_CompleteActivityWorkItem_Call struct {
	*mock.Call
}

// CompleteActivityWorkItem is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *backend.ActivityWorkItem
func (_e *Backend_Expecter) CompleteActivityWorkItem(_a0 interface{}, _a1 interface{}) *Backend_CompleteActivityWorkItem_Call {
	return &Backend_CompleteActivityWorkItem_Call{Call: _e.mock.On("CompleteActivityWorkItem", _a0, _a1)}
}

func (_c *Backend_CompleteActivityWorkItem_Call) Run(run func(_a0 context.Context, _a1 *backend.ActivityWorkItem)) *Backend_CompleteActivityWorkItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*backend.ActivityWorkItem))
	})
	return _c
}

func (_c *Backend_CompleteActivityWorkItem_Call) Return(_a0 error) *Backend_CompleteActivityWorkItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Backend_CompleteActivityWorkItem_Call) RunAndReturn(run func(context.Context, *backend.ActivityWorkItem) error) *Backend_CompleteActivityWorkItem_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteWorkflowWorkItem provides a mock function with given fields: _a0, _a1
func (_m *Backend) CompleteWorkflowWorkItem(_a0 context.Context, _a1 *backend.WorkflowWorkItem) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CompleteWorkflowWorkItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *backend.WorkflowWorkItem) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Backend_CompleteWorkflowWorkItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteWorkflowWorkItem'
type Backend_CompleteWorkflowWorkItem_Call struct {
	*mock.Call
}

// CompleteWorkflowWorkItem is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *backend.WorkflowWorkItem
func (_e *Backend_Expecter) CompleteWorkflowWorkItem(_a0 interface{}, _a1 interface{}) *Backend_CompleteWorkflowWorkItem_Call {
	return &Backend_CompleteWorkflowWorkItem_Call{Call: _e.mock.On("CompleteWorkflowWorkItem", _a0, _a1)}
}

func (_c *Backend_CompleteWorkflowWorkItem_Call) Run(run func(_a0 context.Context, _a1 *backend.WorkflowWorkItem)) *Backend_CompleteWorkflowWorkItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*backend.WorkflowWorkItem))
	})
	return _c
}

func (_c *Backend_CompleteWorkflowWorkItem_Call) Return(_a0 error) *Backend_CompleteWorkflowWorkItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Backend_CompleteWorkflowWorkItem_Call) RunAndReturn(run func(context.Context, *backend.WorkflowWorkItem) error) *Backend_CompleteWorkflowWorkItem_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteWorkflowTask provides a mock function with given fields: _a0, _a1
func (_m *Backend) CompleteWorkflowTask(_a0 context.Context, _a1 *protos.WorkflowResponse) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CompleteWorkflowTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *protos.WorkflowResponse) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Backend_CompleteWorkflowTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteWorkflowTask'
type Backend_CompleteWorkflowTask_Call struct {
	*mock.Call
}

// CompleteWorkflowTask is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *protos.WorkflowResponse
func (_e *Backend_Expecter) CompleteWorkflowTask(_a0 interface{}, _a1 interface{}) *Backend_CompleteWorkflowTask_Call {
	return &Backend_CompleteWorkflowTask_Call{Call: _e.mock.On("CompleteWorkflowTask", _a0, _a1)}
}

func (_c *Backend_CompleteWorkflowTask_Call) Run(run func(_a0 context.Context, _a1 *protos.WorkflowResponse)) *Backend_CompleteWorkflowTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*protos.WorkflowResponse))
	})
	return _c
}

func (_c *Backend_CompleteWorkflowTask_Call) Return(_a0 error) *Backend_CompleteWorkflowTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Backend_CompleteWorkflowTask_Call) RunAndReturn(run func(context.Context, *protos.WorkflowResponse) error) *Backend_CompleteWorkflowTask_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWorkflowInstance provides a mock function with given fields: _a0, _a1
func (_m *Backend) CreateWorkflowInstance(_a0 context.Context, _a1 *protos.CreateWorkflowInstanceRequest) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateWorkflowInstance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *protos.CreateWorkflowInstanceRequest) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Backend_CreateWorkflowInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWorkflowInstance'
type Backend_CreateWorkflowInstance_Call struct {
	*mock.Call
}

// CreateWorkflowInstance is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *protos.CreateWorkflowInstanceRequest
func (_e *Backend_Expecter) CreateWorkflowInstance(_a0 interface{}, _a1 interface{}) *Backend_CreateWorkflowInstance_Call {
	return &Backend_CreateWorkflowInstance_Call{Call: _e.mock.On("CreateWorkflowInstance", _a0, _a1)}
}

func (_c *Backend_CreateWorkflowInstance_Call) Run(run func(_a0 context.Context, _a1 *protos.CreateWorkflowInstanceRequest)) *Backend_CreateWorkflowInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*protos.CreateWorkflowInstanceRequest))
	})
	return _c
}

func (_c *Backend_CreateWorkflowInstance_Call) Return(_a0 error) *Backend_CreateWorkflowInstance_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Backend_CreateWorkflowInstance_Call) RunAndReturn(run func(context.Context, *protos.CreateWorkflowInstanceRequest) error) *Backend_CreateWorkflowInstance_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTaskHub provides a mock function with given fields: _a0
func (_m *Backend) CreateTaskHub(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateTaskHub")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Backend_CreateTaskHub_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTaskHub'
type Backend_CreateTaskHub_Call struct {
	*mock.Call
}

// CreateTaskHub is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *Backend_Expecter) CreateTaskHub(_a0 interface{}) *Backend_CreateTaskHub_Call {
	return &Backend_CreateTaskHub_Call{Call: _e.mock.On("CreateTaskHub", _a0)}
}

func (_c *Backend_CreateTaskHub_Call) Run(run func(_a0 context.Context)) *Backend_CreateTaskHub_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Backend_CreateTaskHub_Call) Return(_a0 error) *Backend_CreateTaskHub_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Backend_CreateTaskHub_Call) RunAndReturn(run func(context.Context) error) *Backend_CreateTaskHub_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTaskHub provides a mock function with given fields: _a0
func (_m *Backend) DeleteTaskHub(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTaskHub")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Backend_DeleteTaskHub_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTaskHub'
type Backend_DeleteTaskHub_Call struct {
	*mock.Call
}

// DeleteTaskHub is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *Backend_Expecter) DeleteTaskHub(_a0 interface{}) *Backend_DeleteTaskHub_Call {
	return &Backend_DeleteTaskHub_Call{Call: _e.mock.On("DeleteTaskHub", _a0)}
}

func (_c *Backend_DeleteTaskHub_Call) Run(run func(_a0 context.Context)) *Backend_DeleteTaskHub_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Backend_DeleteTaskHub_Call) Return(_a0 error) *Backend_DeleteTaskHub_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Backend_DeleteTaskHub_Call) RunAndReturn(run func(context.Context) error) *Backend_DeleteTaskHub_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstanceHistory provides a mock function with given fields: ctx, req
func (_m *Backend) GetInstanceHistory(ctx context.Context, req *protos.GetInstanceHistoryRequest) (*protos.GetInstanceHistoryResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetInstanceHistory")
	}

	var r0 *protos.GetInstanceHistoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *protos.GetInstanceHistoryRequest) (*protos.GetInstanceHistoryResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *protos.GetInstanceHistoryRequest) *protos.GetInstanceHistoryResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*protos.GetInstanceHistoryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *protos.GetInstanceHistoryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Backend_GetInstanceHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstanceHistory'
type Backend_GetInstanceHistory_Call struct {
	*mock.Call
}

// GetInstanceHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - req *protos.GetInstanceHistoryRequest
func (_e *Backend_Expecter) GetInstanceHistory(ctx interface{}, req interface{}) *Backend_GetInstanceHistory_Call {
	return &Backend_GetInstanceHistory_Call{Call: _e.mock.On("GetInstanceHistory", ctx, req)}
}

func (_c *Backend_GetInstanceHistory_Call) Run(run func(ctx context.Context, req *protos.GetInstanceHistoryRequest)) *Backend_GetInstanceHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*protos.GetInstanceHistoryRequest))
	})
	return _c
}

func (_c *Backend_GetInstanceHistory_Call) Return(_a0 *protos.GetInstanceHistoryResponse, _a1 error) *Backend_GetInstanceHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Backend_GetInstanceHistory_Call) RunAndReturn(run func(context.Context, *protos.GetInstanceHistoryRequest) (*protos.GetInstanceHistoryResponse, error)) *Backend_GetInstanceHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkflowMetadata provides a mock function with given fields: _a0, _a1, _a2
func (_m *Backend) GetWorkflowMetadata(_a0 context.Context, _a1 api.InstanceID, _a2 *protos.TaskRouter) (*protos.WorkflowMetadata, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkflowMetadata")
	}

	var r0 *protos.WorkflowMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, api.InstanceID, *protos.TaskRouter) (*protos.WorkflowMetadata, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, api.InstanceID, *protos.TaskRouter) *protos.WorkflowMetadata); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*protos.WorkflowMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, api.InstanceID, *protos.TaskRouter) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Backend_GetWorkflowMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkflowMetadata'
type Backend_GetWorkflowMetadata_Call struct {
	*mock.Call
}

// GetWorkflowMetadata is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 api.InstanceID
//   - _a2 *protos.TaskRouter
func (_e *Backend_Expecter) GetWorkflowMetadata(_a0 interface{}, _a1 interface{}, _a2 interface{}) *Backend_GetWorkflowMetadata_Call {
	return &Backend_GetWorkflowMetadata_Call{Call: _e.mock.On("GetWorkflowMetadata", _a0, _a1, _a2)}
}

func (_c *Backend_GetWorkflowMetadata_Call) Run(run func(_a0 context.Context, _a1 api.InstanceID, _a2 *protos.TaskRouter)) *Backend_GetWorkflowMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(api.InstanceID), args[2].(*protos.TaskRouter))
	})
	return _c
}

func (_c *Backend_GetWorkflowMetadata_Call) Return(_a0 *protos.WorkflowMetadata, _a1 error) *Backend_GetWorkflowMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Backend_GetWorkflowMetadata_Call) RunAndReturn(run func(context.Context, api.InstanceID, *protos.TaskRouter) (*protos.WorkflowMetadata, error)) *Backend_GetWorkflowMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkflowRuntimeState provides a mock function with given fields: _a0, _a1
func (_m *Backend) GetWorkflowRuntimeState(_a0 context.Context, _a1 *backend.WorkflowWorkItem) (*protos.WorkflowRuntimeState, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkflowRuntimeState")
	}

	var r0 *protos.WorkflowRuntimeState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *backend.WorkflowWorkItem) (*protos.WorkflowRuntimeState, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *backend.WorkflowWorkItem) *protos.WorkflowRuntimeState); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*protos.WorkflowRuntimeState)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *backend.WorkflowWorkItem) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Backend_GetWorkflowRuntimeState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkflowRuntimeState'
type Backend_GetWorkflowRuntimeState_Call struct {
	*mock.Call
}

// GetWorkflowRuntimeState is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *backend.WorkflowWorkItem
func (_e *Backend_Expecter) GetWorkflowRuntimeState(_a0 interface{}, _a1 interface{}) *Backend_GetWorkflowRuntimeState_Call {
	return &Backend_GetWorkflowRuntimeState_Call{Call: _e.mock.On("GetWorkflowRuntimeState", _a0, _a1)}
}

func (_c *Backend_GetWorkflowRuntimeState_Call) Run(run func(_a0 context.Context, _a1 *backend.WorkflowWorkItem)) *Backend_GetWorkflowRuntimeState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*backend.WorkflowWorkItem))
	})
	return _c
}

func (_c *Backend_GetWorkflowRuntimeState_Call) Return(_a0 *protos.WorkflowRuntimeState, _a1 error) *Backend_GetWorkflowRuntimeState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Backend_GetWorkflowRuntimeState_Call) RunAndReturn(run func(context.Context, *backend.WorkflowWorkItem) (*protos.WorkflowRuntimeState, error)) *Backend_GetWorkflowRuntimeState_Call {
	_c.Call.Return(run)
	return _c
}

// ListInstanceIDs provides a mock function with given fields: ctx, req
func (_m *Backend) ListInstanceIDs(ctx context.Context, req *protos.ListInstanceIDsRequest) (*protos.ListInstanceIDsResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListInstanceIDs")
	}

	var r0 *protos.ListInstanceIDsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *protos.ListInstanceIDsRequest) (*protos.ListInstanceIDsResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *protos.ListInstanceIDsRequest) *protos.ListInstanceIDsResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*protos.ListInstanceIDsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *protos.ListInstanceIDsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Backend_ListInstanceIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInstanceIDs'
type Backend_ListInstanceIDs_Call struct {
	*mock.Call
}

// ListInstanceIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - req *protos.ListInstanceIDsRequest
func (_e *Backend_Expecter) ListInstanceIDs(ctx interface{}, req interface{}) *Backend_ListInstanceIDs_Call {
	return &Backend_ListInstanceIDs_Call{Call: _e.mock.On("ListInstanceIDs", ctx, req)}
}

func (_c *Backend_ListInstanceIDs_Call) Run(run func(ctx context.Context, req *protos.ListInstanceIDsRequest)) *Backend_ListInstanceIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*protos.ListInstanceIDsRequest))
	})
	return _c
}

func (_c *Backend_ListInstanceIDs_Call) Return(_a0 *protos.ListInstanceIDsResponse, _a1 error) *Backend_ListInstanceIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Backend_ListInstanceIDs_Call) RunAndReturn(run func(context.Context, *protos.ListInstanceIDsRequest) (*protos.ListInstanceIDsResponse, error)) *Backend_ListInstanceIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NextActivityWorkItem provides a mock function with given fields: _a0
func (_m *Backend) NextActivityWorkItem(_a0 context.Context) (*backend.ActivityWorkItem, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for NextActivityWorkItem")
	}

	var r0 *backend.ActivityWorkItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*backend.ActivityWorkItem, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *backend.ActivityWorkItem); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backend.ActivityWorkItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Backend_NextActivityWorkItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextActivityWorkItem'
type Backend_NextActivityWorkItem_Call struct {
	*mock.Call
}

// NextActivityWorkItem is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *Backend_Expecter) NextActivityWorkItem(_a0 interface{}) *Backend_NextActivityWorkItem_Call {
	return &Backend_NextActivityWorkItem_Call{Call: _e.mock.On("NextActivityWorkItem", _a0)}
}

func (_c *Backend_NextActivityWorkItem_Call) Run(run func(_a0 context.Context)) *Backend_NextActivityWorkItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Backend_NextActivityWorkItem_Call) Return(_a0 *backend.ActivityWorkItem, _a1 error) *Backend_NextActivityWorkItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Backend_NextActivityWorkItem_Call) RunAndReturn(run func(context.Context) (*backend.ActivityWorkItem, error)) *Backend_NextActivityWorkItem_Call {
	_c.Call.Return(run)
	return _c
}

// NextWorkflowWorkItem provides a mock function with given fields: _a0
func (_m *Backend) NextWorkflowWorkItem(_a0 context.Context) (*backend.WorkflowWorkItem, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for NextWorkflowWorkItem")
	}

	var r0 *backend.WorkflowWorkItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*backend.WorkflowWorkItem, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *backend.WorkflowWorkItem); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backend.WorkflowWorkItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Backend_NextWorkflowWorkItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextWorkflowWorkItem'
type Backend_NextWorkflowWorkItem_Call struct {
	*mock.Call
}

// NextWorkflowWorkItem is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *Backend_Expecter) NextWorkflowWorkItem(_a0 interface{}) *Backend_NextWorkflowWorkItem_Call {
	return &Backend_NextWorkflowWorkItem_Call{Call: _e.mock.On("NextWorkflowWorkItem", _a0)}
}

func (_c *Backend_NextWorkflowWorkItem_Call) Run(run func(_a0 context.Context)) *Backend_NextWorkflowWorkItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Backend_NextWorkflowWorkItem_Call) Return(_a0 *backend.WorkflowWorkItem, _a1 error) *Backend_NextWorkflowWorkItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Backend_NextWorkflowWorkItem_Call) RunAndReturn(run func(context.Context) (*backend.WorkflowWorkItem, error)) *Backend_NextWorkflowWorkItem_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeWorkflowState provides a mock function with given fields: ctx, id, router, recursive, force
func (_m *Backend) PurgeWorkflowState(ctx context.Context, id api.InstanceID, router *protos.TaskRouter, recursive bool, force bool) (int, error) {
	ret := _m.Called(ctx, id, router, recursive, force)

	if len(ret) == 0 {
		panic("no return value specified for PurgeWorkflowState")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, api.InstanceID, *protos.TaskRouter, bool, bool) (int, error)); ok {
		return rf(ctx, id, router, recursive, force)
	}
	if rf, ok := ret.Get(0).(func(context.Context, api.InstanceID, *protos.TaskRouter, bool, bool) int); ok {
		r0 = rf(ctx, id, router, recursive, force)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, api.InstanceID, *protos.TaskRouter, bool, bool) error); ok {
		r1 = rf(ctx, id, router, recursive, force)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Backend_PurgeWorkflowState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeWorkflowState'
type Backend_PurgeWorkflowState_Call struct {
	*mock.Call
}

// PurgeWorkflowState is a helper method to define mock.On call
//   - ctx context.Context
//   - id api.InstanceID
//   - router *protos.TaskRouter
//   - recursive bool
//   - force bool
func (_e *Backend_Expecter) PurgeWorkflowState(ctx interface{}, id interface{}, router interface{}, recursive interface{}, force interface{}) *Backend_PurgeWorkflowState_Call {
	return &Backend_PurgeWorkflowState_Call{Call: _e.mock.On("PurgeWorkflowState", ctx, id, router, recursive, force)}
}

func (_c *Backend_PurgeWorkflowState_Call) Run(run func(ctx context.Context, id api.InstanceID, router *protos.TaskRouter, recursive bool, force bool)) *Backend_PurgeWorkflowState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(api.InstanceID), args[2].(*protos.TaskRouter), args[3].(bool), args[4].(bool))
	})
	return _c
}

func (_c *Backend_PurgeWorkflowState_Call) Return(_a0 int, _a1 error) *Backend_PurgeWorkflowState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Backend_PurgeWorkflowState_Call) RunAndReturn(run func(context.Context, api.InstanceID, *protos.TaskRouter, bool, bool) (int, error)) *Backend_PurgeWorkflowState_Call {
	_c.Call.Return(run)
	return _c
}

// RerunWorkflowFromEvent provides a mock function with given fields: ctx, req
func (_m *Backend) RerunWorkflowFromEvent(ctx context.Context, req *protos.RerunWorkflowFromEventRequest) (api.InstanceID, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RerunWorkflowFromEvent")
	}

	var r0 api.InstanceID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *protos.RerunWorkflowFromEventRequest) (api.InstanceID, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *protos.RerunWorkflowFromEventRequest) api.InstanceID); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(api.InstanceID)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *protos.RerunWorkflowFromEventRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Backend_RerunWorkflowFromEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RerunWorkflowFromEvent'
type Backend_RerunWorkflowFromEvent_Call struct {
	*mock.Call
}

// RerunWorkflowFromEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - req *protos.RerunWorkflowFromEventRequest
func (_e *Backend_Expecter) RerunWorkflowFromEvent(ctx interface{}, req interface{}) *Backend_RerunWorkflowFromEvent_Call {
	return &Backend_RerunWorkflowFromEvent_Call{Call: _e.mock.On("RerunWorkflowFromEvent", ctx, req)}
}

func (_c *Backend_RerunWorkflowFromEvent_Call) Run(run func(ctx context.Context, req *protos.RerunWorkflowFromEventRequest)) *Backend_RerunWorkflowFromEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*protos.RerunWorkflowFromEventRequest))
	})
	return _c
}

func (_c *Backend_RerunWorkflowFromEvent_Call) Return(_a0 api.InstanceID, _a1 error) *Backend_RerunWorkflowFromEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Backend_RerunWorkflowFromEvent_Call) RunAndReturn(run func(context.Context, *protos.RerunWorkflowFromEventRequest) (api.InstanceID, error)) *Backend_RerunWorkflowFromEvent_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: _a0
func (_m *Backend) Start(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Backend_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type Backend_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *Backend_Expecter) Start(_a0 interface{}) *Backend_Start_Call {
	return &Backend_Start_Call{Call: _e.mock.On("Start", _a0)}
}

func (_c *Backend_Start_Call) Run(run func(_a0 context.Context)) *Backend_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Backend_Start_Call) Return(_a0 error) *Backend_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Backend_Start_Call) RunAndReturn(run func(context.Context) error) *Backend_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with given fields: _a0
func (_m *Backend) Stop(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Backend_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type Backend_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *Backend_Expecter) Stop(_a0 interface{}) *Backend_Stop_Call {
	return &Backend_Stop_Call{Call: _e.mock.On("Stop", _a0)}
}

func (_c *Backend_Stop_Call) Run(run func(_a0 context.Context)) *Backend_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Backend_Stop_Call) Return(_a0 error) *Backend_Stop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Backend_Stop_Call) RunAndReturn(run func(context.Context) error) *Backend_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForActivityCompletion provides a mock function with given fields: _a0
func (_m *Backend) WaitForActivityCompletion(_a0 *protos.ActivityRequest) func(context.Context) (*protos.ActivityResponse, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for WaitForActivityCompletion")
	}

	var r0 func(context.Context) (*protos.ActivityResponse, error)
	if rf, ok := ret.Get(0).(func(*protos.ActivityRequest) func(context.Context) (*protos.ActivityResponse, error)); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(context.Context) (*protos.ActivityResponse, error))
		}
	}

	return r0
}

// Backend_WaitForActivityCompletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForActivityCompletion'
type Backend_WaitForActivityCompletion_Call struct {
	*mock.Call
}

// WaitForActivityCompletion is a helper method to define mock.On call
//   - _a0 *protos.ActivityRequest
func (_e *Backend_Expecter) WaitForActivityCompletion(_a0 interface{}) *Backend_WaitForActivityCompletion_Call {
	return &Backend_WaitForActivityCompletion_Call{Call: _e.mock.On("WaitForActivityCompletion", _a0)}
}

func (_c *Backend_WaitForActivityCompletion_Call) Run(run func(_a0 *protos.ActivityRequest)) *Backend_WaitForActivityCompletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*protos.ActivityRequest))
	})
	return _c
}

func (_c *Backend_WaitForActivityCompletion_Call) Return(_a0 func(context.Context) (*protos.ActivityResponse, error)) *Backend_WaitForActivityCompletion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Backend_WaitForActivityCompletion_Call) RunAndReturn(run func(*protos.ActivityRequest) func(context.Context) (*protos.ActivityResponse, error)) *Backend_WaitForActivityCompletion_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForWorkflowTaskCompletion provides a mock function with given fields: _a0
func (_m *Backend) WaitForWorkflowTaskCompletion(_a0 *protos.WorkflowRequest) func(context.Context) (*protos.WorkflowResponse, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for WaitForWorkflowTaskCompletion")
	}

	var r0 func(context.Context) (*protos.WorkflowResponse, error)
	if rf, ok := ret.Get(0).(func(*protos.WorkflowRequest) func(context.Context) (*protos.WorkflowResponse, error)); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(context.Context) (*protos.WorkflowResponse, error))
		}
	}

	return r0
}

// Backend_WaitForWorkflowTaskCompletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForWorkflowTaskCompletion'
type Backend_WaitForWorkflowTaskCompletion_Call struct {
	*mock.Call
}

// WaitForWorkflowTaskCompletion is a helper method to define mock.On call
//   - _a0 *protos.WorkflowRequest
func (_e *Backend_Expecter) WaitForWorkflowTaskCompletion(_a0 interface{}) *Backend_WaitForWorkflowTaskCompletion_Call {
	return &Backend_WaitForWorkflowTaskCompletion_Call{Call: _e.mock.On("WaitForWorkflowTaskCompletion", _a0)}
}

func (_c *Backend_WaitForWorkflowTaskCompletion_Call) Run(run func(_a0 *protos.WorkflowRequest)) *Backend_WaitForWorkflowTaskCompletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*protos.WorkflowRequest))
	})
	return _c
}

func (_c *Backend_WaitForWorkflowTaskCompletion_Call) Return(_a0 func(context.Context) (*protos.WorkflowResponse, error)) *Backend_WaitForWorkflowTaskCompletion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Backend_WaitForWorkflowTaskCompletion_Call) RunAndReturn(run func(*protos.WorkflowRequest) func(context.Context) (*protos.WorkflowResponse, error)) *Backend_WaitForWorkflowTaskCompletion_Call {
	_c.Call.Return(run)
	return _c
}

// WatchWorkflowRuntimeStatus provides a mock function with given fields: ctx, id, router, condition
func (_m *Backend) WatchWorkflowRuntimeStatus(ctx context.Context, id api.InstanceID, router *protos.TaskRouter, condition func(*protos.WorkflowMetadata) bool) error {
	ret := _m.Called(ctx, id, router, condition)

	if len(ret) == 0 {
		panic("no return value specified for WatchWorkflowRuntimeStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, api.InstanceID, *protos.TaskRouter, func(*protos.WorkflowMetadata) bool) error); ok {
		r0 = rf(ctx, id, router, condition)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Backend_WatchWorkflowRuntimeStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchWorkflowRuntimeStatus'
type Backend_WatchWorkflowRuntimeStatus_Call struct {
	*mock.Call
}

// WatchWorkflowRuntimeStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id api.InstanceID
//   - router *protos.TaskRouter
//   - condition func(*protos.WorkflowMetadata) bool
func (_e *Backend_Expecter) WatchWorkflowRuntimeStatus(ctx interface{}, id interface{}, router interface{}, condition interface{}) *Backend_WatchWorkflowRuntimeStatus_Call {
	return &Backend_WatchWorkflowRuntimeStatus_Call{Call: _e.mock.On("WatchWorkflowRuntimeStatus", ctx, id, router, condition)}
}

func (_c *Backend_WatchWorkflowRuntimeStatus_Call) Run(run func(ctx context.Context, id api.InstanceID, router *protos.TaskRouter, condition func(*protos.WorkflowMetadata) bool)) *Backend_WatchWorkflowRuntimeStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(api.InstanceID), args[2].(*protos.TaskRouter), args[3].(func(*protos.WorkflowMetadata) bool))
	})
	return _c
}

func (_c *Backend_WatchWorkflowRuntimeStatus_Call) Return(_a0 error) *Backend_WatchWorkflowRuntimeStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Backend_WatchWorkflowRuntimeStatus_Call) RunAndReturn(run func(context.Context, api.InstanceID, *protos.TaskRouter, func(*protos.WorkflowMetadata) bool) error) *Backend_WatchWorkflowRuntimeStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewBackend creates a new instance of Backend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *Backend {
	mock := &Backend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
