// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.1
// source: orchestrator_service.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TaskHubSidecarService_Hello_FullMethodName                     = "/TaskHubSidecarService/Hello"
	TaskHubSidecarService_StartInstance_FullMethodName             = "/TaskHubSidecarService/StartInstance"
	TaskHubSidecarService_GetInstance_FullMethodName               = "/TaskHubSidecarService/GetInstance"
	TaskHubSidecarService_WaitForInstanceStart_FullMethodName      = "/TaskHubSidecarService/WaitForInstanceStart"
	TaskHubSidecarService_WaitForInstanceCompletion_FullMethodName = "/TaskHubSidecarService/WaitForInstanceCompletion"
	TaskHubSidecarService_RaiseEvent_FullMethodName                = "/TaskHubSidecarService/RaiseEvent"
	TaskHubSidecarService_TerminateInstance_FullMethodName         = "/TaskHubSidecarService/TerminateInstance"
	TaskHubSidecarService_SuspendInstance_FullMethodName           = "/TaskHubSidecarService/SuspendInstance"
	TaskHubSidecarService_ResumeInstance_FullMethodName            = "/TaskHubSidecarService/ResumeInstance"
	TaskHubSidecarService_PurgeInstances_FullMethodName            = "/TaskHubSidecarService/PurgeInstances"
	TaskHubSidecarService_GetWorkItems_FullMethodName              = "/TaskHubSidecarService/GetWorkItems"
	TaskHubSidecarService_CompleteActivityTask_FullMethodName      = "/TaskHubSidecarService/CompleteActivityTask"
	TaskHubSidecarService_CompleteOrchestratorTask_FullMethodName  = "/TaskHubSidecarService/CompleteOrchestratorTask"
	TaskHubSidecarService_CompleteWorkflowTask_FullMethodName      = "/TaskHubSidecarService/CompleteWorkflowTask"
	TaskHubSidecarService_ListInstanceIDs_FullMethodName           = "/TaskHubSidecarService/ListInstanceIDs"
	TaskHubSidecarService_GetInstanceHistory_FullMethodName        = "/TaskHubSidecarService/GetInstanceHistory"
)

// TaskHubSidecarServiceClient is the client API for TaskHubSidecarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskHubSidecarServiceClient interface {
	// Sends a hello request to the sidecar service.
	Hello(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Starts a new workflow instance.
	StartInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*CreateInstanceResponse, error)
	// Gets the status of an existing workflow instance.
	GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error)
	// Waits for a workflow instance to reach a running or completion state.
	WaitForInstanceStart(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error)
	// Waits for a workflow instance to reach a completion state (completed, failed, terminated, etc.).
	WaitForInstanceCompletion(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error)
	// Raises an event to a running workflow instance.
	RaiseEvent(ctx context.Context, in *RaiseEventRequest, opts ...grpc.CallOption) (*RaiseEventResponse, error)
	// Terminates a running workflow instance.
	TerminateInstance(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*TerminateResponse, error)
	// Suspends a running workflow instance.
	SuspendInstance(ctx context.Context, in *SuspendRequest, opts ...grpc.CallOption) (*SuspendResponse, error)
	// Resumes a suspended workflow instance.
	ResumeInstance(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*ResumeResponse, error)
	PurgeInstances(ctx context.Context, in *PurgeInstancesRequest, opts ...grpc.CallOption) (*PurgeInstancesResponse, error)
	GetWorkItems(ctx context.Context, in *GetWorkItemsRequest, opts ...grpc.CallOption) (TaskHubSidecarService_GetWorkItemsClient, error)
	CompleteActivityTask(ctx context.Context, in *ActivityResponse, opts ...grpc.CallOption) (*CompleteTaskResponse, error)
	// Deprecated: Do not use.
	// Deprecated: Use CompleteWorkflowTask instead.
	CompleteOrchestratorTask(ctx context.Context, in *WorkflowResponse, opts ...grpc.CallOption) (*CompleteTaskResponse, error)
	// Completes a workflow work item.
	CompleteWorkflowTask(ctx context.Context, in *WorkflowResponse, opts ...grpc.CallOption) (*CompleteTaskResponse, error)
	ListInstanceIDs(ctx context.Context, in *ListInstanceIDsRequest, opts ...grpc.CallOption) (*ListInstanceIDsResponse, error)
	GetInstanceHistory(ctx context.Context, in *GetInstanceHistoryRequest, opts ...grpc.CallOption) (*GetInstanceHistoryResponse, error)
}

type taskHubSidecarServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskHubSidecarServiceClient(cc grpc.ClientConnInterface) TaskHubSidecarServiceClient {
	return &taskHubSidecarServiceClient{cc}
}

func (c *taskHubSidecarServiceClient) Hello(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_Hello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) StartInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*CreateInstanceResponse, error) {
	out := new(CreateInstanceResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_StartInstance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error) {
	out := new(GetInstanceResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_GetInstance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) WaitForInstanceStart(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error) {
	out := new(GetInstanceResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_WaitForInstanceStart_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) WaitForInstanceCompletion(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error) {
	out := new(GetInstanceResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_WaitForInstanceCompletion_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) RaiseEvent(ctx context.Context, in *RaiseEventRequest, opts ...grpc.CallOption) (*RaiseEventResponse, error) {
	out := new(RaiseEventResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_RaiseEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) TerminateInstance(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*TerminateResponse, error) {
	out := new(TerminateResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_TerminateInstance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) SuspendInstance(ctx context.Context, in *SuspendRequest, opts ...grpc.CallOption) (*SuspendResponse, error) {
	out := new(SuspendResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_SuspendInstance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) ResumeInstance(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*ResumeResponse, error) {
	out := new(ResumeResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_ResumeInstance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) PurgeInstances(ctx context.Context, in *PurgeInstancesRequest, opts ...grpc.CallOption) (*PurgeInstancesResponse, error) {
	out := new(PurgeInstancesResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_PurgeInstances_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) GetWorkItems(ctx context.Context, in *GetWorkItemsRequest, opts ...grpc.CallOption) (TaskHubSidecarService_GetWorkItemsClient, error) {
	stream, err := c.cc.NewStream(ctx, &TaskHubSidecarService_ServiceDesc.Streams[0], TaskHubSidecarService_GetWorkItems_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &taskHubSidecarServiceGetWorkItemsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TaskHubSidecarService_GetWorkItemsClient interface {
	Recv() (*WorkItem, error)
	grpc.ClientStream
}

type taskHubSidecarServiceGetWorkItemsClient struct {
	grpc.ClientStream
}

func (x *taskHubSidecarServiceGetWorkItemsClient) Recv() (*WorkItem, error) {
	m := new(WorkItem)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *taskHubSidecarServiceClient) CompleteActivityTask(ctx context.Context, in *ActivityResponse, opts ...grpc.CallOption) (*CompleteTaskResponse, error) {
	out := new(CompleteTaskResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_CompleteActivityTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *taskHubSidecarServiceClient) CompleteOrchestratorTask(ctx context.Context, in *WorkflowResponse, opts ...grpc.CallOption) (*CompleteTaskResponse, error) {
	out := new(CompleteTaskResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_CompleteOrchestratorTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) CompleteWorkflowTask(ctx context.Context, in *WorkflowResponse, opts ...grpc.CallOption) (*CompleteTaskResponse, error) {
	out := new(CompleteTaskResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_CompleteWorkflowTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) ListInstanceIDs(ctx context.Context, in *ListInstanceIDsRequest, opts ...grpc.CallOption) (*ListInstanceIDsResponse, error) {
	out := new(ListInstanceIDsResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_ListInstanceIDs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskHubSidecarServiceClient) GetInstanceHistory(ctx context.Context, in *GetInstanceHistoryRequest, opts ...grpc.CallOption) (*GetInstanceHistoryResponse, error) {
	out := new(GetInstanceHistoryResponse)
	err := c.cc.Invoke(ctx, TaskHubSidecarService_GetInstanceHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskHubSidecarServiceServer is the server API for TaskHubSidecarService service.
// All implementations must embed UnimplementedTaskHubSidecarServiceServer
// for forward compatibility
type TaskHubSidecarServiceServer interface {
	// Sends a hello request to the sidecar service.
	Hello(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// Starts a new workflow instance.
	StartInstance(context.Context, *CreateInstanceRequest) (*CreateInstanceResponse, error)
	// Gets the status of an existing workflow instance.
	GetInstance(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error)
	// Waits for a workflow instance to reach a running or completion state.
	WaitForInstanceStart(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error)
	// Waits for a workflow instance to reach a completion state (completed, failed, terminated, etc.).
	WaitForInstanceCompletion(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error)
	// Raises an event to a running workflow instance.
	RaiseEvent(context.Context, *RaiseEventRequest) (*RaiseEventResponse, error)
	// Terminates a running workflow instance.
	TerminateInstance(context.Context, *TerminateRequest) (*TerminateResponse, error)
	// Suspends a running workflow instance.
	SuspendInstance(context.Context, *SuspendRequest) (*SuspendResponse, error)
	// Resumes a suspended workflow instance.
	ResumeInstance(context.Context, *ResumeRequest) (*ResumeResponse, error)
	PurgeInstances(context.Context, *PurgeInstancesRequest) (*PurgeInstancesResponse, error)
	GetWorkItems(*GetWorkItemsRequest, TaskHubSidecarService_GetWorkItemsServer) error
	CompleteActivityTask(context.Context, *ActivityResponse) (*CompleteTaskResponse, error)
	// Deprecated: Do not use.
	// Deprecated: Use CompleteWorkflowTask instead.
	CompleteOrchestratorTask(context.Context, *WorkflowResponse) (*CompleteTaskResponse, error)
	// Completes a workflow work item.
	CompleteWorkflowTask(context.Context, *WorkflowResponse) (*CompleteTaskResponse, error)
	ListInstanceIDs(context.Context, *ListInstanceIDsRequest) (*ListInstanceIDsResponse, error)
	GetInstanceHistory(context.Context, *GetInstanceHistoryRequest) (*GetInstanceHistoryResponse, error)
	mustEmbedUnimplementedTaskHubSidecarServiceServer()
}

// UnimplementedTaskHubSidecarServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTaskHubSidecarServiceServer struct {
}

func (UnimplementedTaskHubSidecarServiceServer) Hello(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) StartInstance(context.Context, *CreateInstanceRequest) (*CreateInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartInstance not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) GetInstance(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInstance not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) WaitForInstanceStart(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitForInstanceStart not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) WaitForInstanceCompletion(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitForInstanceCompletion not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) RaiseEvent(context.Context, *RaiseEventRequest) (*RaiseEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RaiseEvent not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) TerminateInstance(context.Context, *TerminateRequest) (*TerminateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TerminateInstance not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) SuspendInstance(context.Context, *SuspendRequest) (*SuspendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuspendInstance not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) ResumeInstance(context.Context, *ResumeRequest) (*ResumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeInstance not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) PurgeInstances(context.Context, *PurgeInstancesRequest) (*PurgeInstancesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurgeInstances not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) GetWorkItems(*GetWorkItemsRequest, TaskHubSidecarService_GetWorkItemsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetWorkItems not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) CompleteActivityTask(context.Context, *ActivityResponse) (*CompleteTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteActivityTask not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) CompleteOrchestratorTask(context.Context, *WorkflowResponse) (*CompleteTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteOrchestratorTask not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) CompleteWorkflowTask(context.Context, *WorkflowResponse) (*CompleteTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteWorkflowTask not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) ListInstanceIDs(context.Context, *ListInstanceIDsRequest) (*ListInstanceIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInstanceIDs not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) GetInstanceHistory(context.Context, *GetInstanceHistoryRequest) (*GetInstanceHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInstanceHistory not implemented")
}
func (UnimplementedTaskHubSidecarServiceServer) mustEmbedUnimplementedTaskHubSidecarServiceServer() {}

// UnsafeTaskHubSidecarServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskHubSidecarServiceServer will
// result in compilation errors.
type UnsafeTaskHubSidecarServiceServer interface {
	mustEmbedUnimplementedTaskHubSidecarServiceServer()
}

func RegisterTaskHubSidecarServiceServer(s grpc.ServiceRegistrar, srv TaskHubSidecarServiceServer) {
	s.RegisterService(&TaskHubSidecarService_ServiceDesc, srv)
}

func _TaskHubSidecarService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).Hello(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_StartInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).StartInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_StartInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).StartInstance(ctx, req.(*CreateInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_GetInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).GetInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_GetInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).GetInstance(ctx, req.(*GetInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_WaitForInstanceStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).WaitForInstanceStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_WaitForInstanceStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).WaitForInstanceStart(ctx, req.(*GetInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_WaitForInstanceCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).WaitForInstanceCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_WaitForInstanceCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).WaitForInstanceCompletion(ctx, req.(*GetInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_RaiseEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RaiseEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).RaiseEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_RaiseEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).RaiseEvent(ctx, req.(*RaiseEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_TerminateInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).TerminateInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_TerminateInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).TerminateInstance(ctx, req.(*TerminateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_SuspendInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).SuspendInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_SuspendInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).SuspendInstance(ctx, req.(*SuspendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_ResumeInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).ResumeInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_ResumeInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).ResumeInstance(ctx, req.(*ResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_PurgeInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).PurgeInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_PurgeInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).PurgeInstances(ctx, req.(*PurgeInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_GetWorkItems_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetWorkItemsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TaskHubSidecarServiceServer).GetWorkItems(m, &taskHubSidecarServiceGetWorkItemsServer{stream})
}

type TaskHubSidecarService_GetWorkItemsServer interface {
	Send(*WorkItem) error
	grpc.ServerStream
}

type taskHubSidecarServiceGetWorkItemsServer struct {
	grpc.ServerStream
}

func (x *taskHubSidecarServiceGetWorkItemsServer) Send(m *WorkItem) error {
	return x.ServerStream.SendMsg(m)
}

func _TaskHubSidecarService_CompleteActivityTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivityResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).CompleteActivityTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_CompleteActivityTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).CompleteActivityTask(ctx, req.(*ActivityResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_CompleteOrchestratorTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).CompleteOrchestratorTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_CompleteOrchestratorTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).CompleteOrchestratorTask(ctx, req.(*WorkflowResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_CompleteWorkflowTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).CompleteWorkflowTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_CompleteWorkflowTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).CompleteWorkflowTask(ctx, req.(*WorkflowResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_ListInstanceIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstanceIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).ListInstanceIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_ListInstanceIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).ListInstanceIDs(ctx, req.(*ListInstanceIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskHubSidecarService_GetInstanceHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskHubSidecarServiceServer).GetInstanceHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskHubSidecarService_GetInstanceHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskHubSidecarServiceServer).GetInstanceHistory(ctx, req.(*GetInstanceHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskHubSidecarService_ServiceDesc is the grpc.ServiceDesc for TaskHubSidecarService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskHubSidecarService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TaskHubSidecarService",
	HandlerType: (*TaskHubSidecarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _TaskHubSidecarService_Hello_Handler,
		},
		{
			MethodName: "StartInstance",
			Handler:    _TaskHubSidecarService_StartInstance_Handler,
		},
		{
			MethodName: "GetInstance",
			Handler:    _TaskHubSidecarService_GetInstance_Handler,
		},
		{
			MethodName: "WaitForInstanceStart",
			Handler:    _TaskHubSidecarService_WaitForInstanceStart_Handler,
		},
		{
			MethodName: "WaitForInstanceCompletion",
			Handler:    _TaskHubSidecarService_WaitForInstanceCompletion_Handler,
		},
		{
			MethodName: "RaiseEvent",
			Handler:    _TaskHubSidecarService_RaiseEvent_Handler,
		},
		{
			MethodName: "TerminateInstance",
			Handler:    _TaskHubSidecarService_TerminateInstance_Handler,
		},
		{
			MethodName: "SuspendInstance",
			Handler:    _TaskHubSidecarService_SuspendInstance_Handler,
		},
		{
			MethodName: "ResumeInstance",
			Handler:    _TaskHubSidecarService_ResumeInstance_Handler,
		},
		{
			MethodName: "PurgeInstances",
			Handler:    _TaskHubSidecarService_PurgeInstances_Handler,
		},
		{
			MethodName: "CompleteActivityTask",
			Handler:    _TaskHubSidecarService_CompleteActivityTask_Handler,
		},
		{
			MethodName: "CompleteOrchestratorTask",
			Handler:    _TaskHubSidecarService_CompleteOrchestratorTask_Handler,
		},
		{
			MethodName: "CompleteWorkflowTask",
			Handler:    _TaskHubSidecarService_CompleteWorkflowTask_Handler,
		},
		{
			MethodName: "ListInstanceIDs",
			Handler:    _TaskHubSidecarService_ListInstanceIDs_Handler,
		},
		{
			MethodName: "GetInstanceHistory",
			Handler:    _TaskHubSidecarService_GetInstanceHistory_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetWorkItems",
			Handler:       _TaskHubSidecarService_GetWorkItems_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "orchestrator_service.proto",
}
