// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: orchestrator_service.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerCapability int32

const (
	WorkerCapability_WORKER_CAPABILITY_UNSPECIFIED WorkerCapability = 0
	// Indicates that the worker retains an instance's accumulated history in
	// memory between workflow turns on the same work-item stream, so that the
	// service can send only the new events (the delta) instead of the full
	// history each turn. When the service has dispatched a turn for an
	// instance to this stream and believes the stream is still warm for it, it
	// may set WorkflowRequest.cachedHistory and drop the committed-history
	// prefix the worker already holds from pastEvents, leaving only the delta
	// there. On a cache miss the worker recovers the full history via the
	// GetInstanceHistory RPC, so the optimization never affects correctness.
	WorkerCapability_WORKER_CAPABILITY_STATEFUL_HISTORY WorkerCapability = 2
)

// Enum value maps for WorkerCapability.
var (
	WorkerCapability_name = map[int32]string{
		0: "WORKER_CAPABILITY_UNSPECIFIED",
		2: "WORKER_CAPABILITY_STATEFUL_HISTORY",
	}
	WorkerCapability_value = map[string]int32{
		"WORKER_CAPABILITY_UNSPECIFIED":      0,
		"WORKER_CAPABILITY_STATEFUL_HISTORY": 2,
	}
)

func (x WorkerCapability) Enum() *WorkerCapability {
	p := new(WorkerCapability)
	*p = x
	return p
}

func (x WorkerCapability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerCapability) Descriptor() protoreflect.EnumDescriptor {
	return file_orchestrator_service_proto_enumTypes[0].Descriptor()
}

func (WorkerCapability) Type() protoreflect.EnumType {
	return &file_orchestrator_service_proto_enumTypes[0]
}

func (x WorkerCapability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerCapability.Descriptor instead.
func (WorkerCapability) EnumDescriptor() ([]byte, []int) {
	return file_orchestrator_service_proto_rawDescGZIP(), []int{0}
}

type ActivityRequest struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	Name               string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version            *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Input              *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	WorkflowInstance   *WorkflowInstance       `protobuf:"bytes,4,opt,name=workflowInstance,proto3" json:"workflowInstance,omitempty"`
	TaskId             int32                   `protobuf:"varint,5,opt,name=taskId,proto3" json:"taskId,omitempty"`
	ParentTraceContext *TraceContext           `protobuf:"bytes,6,opt,name=parentTraceContext,proto3" json:"parentTraceContext,omitempty"`
	TaskExecutionId    string                  `protobuf:"bytes,7,opt,name=taskExecutionId,proto3" json:"taskExecutionId,omitempty"`
	// Propagated history from the calling workflow.
	// Delivered via the work item stream to the SDK, so that the
	// activity function can access it via ctx.
	PropagatedHistory *PropagatedHistory `protobuf:"bytes,8,opt,name=propagatedHistory,proto3,oneof" json:"propagatedHistory,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ActivityRequest) Reset() {
	*x = ActivityRequest{}
	mi := &file_orchestrator_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityRequest) ProtoMessage() {}

func (x *ActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityRequest.ProtoReflect.Descriptor instead.
func (*ActivityRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_proto_rawDescGZIP(), []int{0}
}

func (x *ActivityRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActivityRequest) GetVersion() *wrapperspb.StringValue {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *ActivityRequest) GetInput() *wrapperspb.StringValue {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ActivityRequest) GetWorkflowInstance() *WorkflowInstance {
	if x != nil {
		return x.WorkflowInstance
	}
	return nil
}

func (x *ActivityRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ActivityRequest) GetParentTraceContext() *TraceContext {
	if x != nil {
		return x.ParentTraceContext
	}
	return nil
}

func (x *ActivityRequest) GetTaskExecutionId() string {
	if x != nil {
		return x.TaskExecutionId
	}
	return ""
}

func (x *ActivityRequest) GetPropagatedHistory() *PropagatedHistory {
	if x != nil {
		return x.PropagatedHistory
	}
	return nil
}

type ActivityResponse struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	InstanceId      string                  `protobuf:"bytes,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	TaskId          int32                   `protobuf:"varint,2,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Result          *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	FailureDetails  *TaskFailureDetails     `protobuf:"bytes,4,opt,name=failureDetails,proto3" json:"failureDetails,omitempty"`
	CompletionToken string                  `protobuf:"bytes,5,opt,name=completionToken,proto3" json:"completionToken,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ActivityResponse) Reset() {
	*x = ActivityResponse{}
	mi := &file_orchestrator_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityResponse) ProtoMessage() {}

func (x *ActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityResponse.ProtoReflect.Descriptor instead.
func (*ActivityResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_proto_rawDescGZIP(), []int{1}
}

func (x *ActivityResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ActivityResponse) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ActivityResponse) GetResult() *wrapperspb.StringValue {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ActivityResponse) GetFailureDetails() *TaskFailureDetails {
	if x != nil {
		return x.FailureDetails
	}
	return nil
}

func (x *ActivityResponse) GetCompletionToken() string {
	if x != nil {
		return x.CompletionToken
	}
	return ""
}

// CachedHistory is set on a WorkflowRequest when the service has intentionally
// omitted the committed history prefix the worker is expected to already hold
// for this instance from a previous turn on the same stream (see
// WORKER_CAPABILITY_STATEFUL_HISTORY). Its presence means pastEvents carries
// only the delta since the worker was last brought up to date; its absence
// means pastEvents is the full committed history. The worker reconstructs the
// full past history by prepending its cached events to pastEvents. The service
// only sets this for workers that advertised
// WORKER_CAPABILITY_STATEFUL_HISTORY and that it believes to be warm for the
// instance, so it is always safe for a worker to fall back to the
// GetInstanceHistory RPC.
type CachedHistory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// eventCount is the number of leading (committed) history events the
	// service believes the worker already holds, i.e. the length of the prefix
	// omitted from pastEvents. The worker's cached prefix must contain exactly
	// this many events; if it does not, the worker must treat this as a cache
	// miss and fetch the full history via GetInstanceHistory before applying
	// newEvents.
	EventCount    int32 `protobuf:"varint,1,opt,name=eventCount,proto3" json:"eventCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CachedHistory) Reset() {
	*x = CachedHistory{}
	mi := &file_orchestrator_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CachedHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CachedHistory) ProtoMessage() {}

func (x *CachedHistory) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CachedHistory.ProtoReflect.Descriptor instead.
func (*CachedHistory) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_proto_rawDescGZIP(), []int{2}
}

func (x *CachedHistory) GetEventCount() int32 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

type WorkflowRequest struct {
	state                    protoimpl.MessageState  `protogen:"open.v1"`
	InstanceId               string                  `protobuf:"bytes,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	ExecutionId              *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=executionId,proto3" json:"executionId,omitempty"`
	PastEvents               []*HistoryEvent         `protobuf:"bytes,3,rep,name=pastEvents,proto3" json:"pastEvents,omitempty"`
	NewEvents                []*HistoryEvent         `protobuf:"bytes,4,rep,name=newEvents,proto3" json:"newEvents,omitempty"`
	RequiresHistoryStreaming bool                    `protobuf:"varint,6,opt,name=requiresHistoryStreaming,proto3" json:"requiresHistoryStreaming,omitempty"`
	Router                   *TaskRouter             `protobuf:"bytes,7,opt,name=router,proto3,oneof" json:"router,omitempty"`
	// Propagated history from a parent workflow.
	// Delivered via the work item stream to the SDK, so that the
	// workflow function can access it via ctx.
	PropagatedHistory *PropagatedHistory `protobuf:"bytes,8,opt,name=propagatedHistory,proto3,oneof" json:"propagatedHistory,omitempty"`
	// cachedHistory, when present, signals that pastEvents holds only the
	// delta and the worker must reconstruct the omitted prefix from its own
	// cache (or fetch it via GetInstanceHistory on a miss). Absent for
	// full-history sends.
	CachedHistory *CachedHistory `protobuf:"bytes,9,opt,name=cachedHistory,proto3,oneof" json:"cachedHistory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowRequest) Reset() {
	*x = WorkflowRequest{}
	mi := &file_orchestrator_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowRequest) ProtoMessage() {}

func (x *WorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowRequest.ProtoReflect.Descriptor instead.
func (*WorkflowRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_proto_rawDescGZIP(), []int{3}
}

func (x *WorkflowRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *WorkflowRequest) GetExecutionId() *wrapperspb.StringValue {
	if x != nil {
		return x.ExecutionId
	}
	return nil
}

func (x *WorkflowRequest) GetPastEvents() []*HistoryEvent {
	if x != nil {
		return x.PastEvents
	}
	return nil
}

func (x *WorkflowRequest) GetNewEvents() []*HistoryEvent {
	if x != nil {
		return x.NewEvents
	}
	return nil
}

func (x *WorkflowRequest) GetRequiresHistoryStreaming() bool {
	if x != nil {
		return x.RequiresHistoryStreaming
	}
	return false
}

func (x *WorkflowRequest) GetRouter() *TaskRouter {
	if x != nil {
		return x.Router
	}
	return nil
}

func (x *WorkflowRequest) GetPropagatedHistory() *PropagatedHistory {
	if x != nil {
		return x.PropagatedHistory
	}
	return nil
}

func (x *WorkflowRequest) GetCachedHistory() *CachedHistory {
	if x != nil {
		return x.CachedHistory
	}
	return nil
}

type WorkflowResponse struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	InstanceId      string                  `protobuf:"bytes,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	Actions         []*WorkflowAction       `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	CustomStatus    *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=customStatus,proto3" json:"customStatus,omitempty"`
	CompletionToken string                  `protobuf:"bytes,4,opt,name=completionToken,proto3" json:"completionToken,omitempty"`
	// The number of work item events that were processed by the workflow.
	// This field is optional. If not set, the service should assume that the workflow processed all events.
	NumEventsProcessed *wrapperspb.Int32Value `protobuf:"bytes,5,opt,name=numEventsProcessed,proto3" json:"numEventsProcessed,omitempty"`
	Version            *WorkflowVersion       `protobuf:"bytes,6,opt,name=version,proto3,oneof" json:"version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WorkflowResponse) Reset() {
	*x = WorkflowResponse{}
	mi := &file_orchestrator_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowResponse) ProtoMessage() {}

func (x *WorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowResponse.ProtoReflect.Descriptor instead.
func (*WorkflowResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_proto_rawDescGZIP(), []int{4}
}

func (x *WorkflowResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *WorkflowResponse) GetActions() []*WorkflowAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *WorkflowResponse) GetCustomStatus() *wrapperspb.StringValue {
	if x != nil {
		return x.CustomStatus
	}
	return nil
}

func (x *WorkflowResponse) GetCompletionToken() string {
	if x != nil {
		return x.CompletionToken
	}
	return ""
}

func (x *WorkflowResponse) GetNumEventsProcessed() *wrapperspb.Int32Value {
	if x != nil {
		return x.NumEventsProcessed
	}
	return nil
}

func (x *WorkflowResponse) GetVersion() *WorkflowVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

type CreateInstanceRequest struct {
	state                   protoimpl.MessageState  `protogen:"open.v1"`
	InstanceId              string                  `protobuf:"bytes,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	Name                    string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version                 *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Input                   *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	ScheduledStartTimestamp *timestamppb.Timestamp  `protobuf:"bytes,5,opt,name=scheduledStartTimestamp,proto3" json:"scheduledStartTimestamp,omitempty"`
	ExecutionId             *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=executionId,proto3" json:"executionId,omitempty"`
	Tags                    map[string]string       `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ParentTraceContext      *TraceContext           `protobuf:"bytes,9,opt,name=parentTraceContext,proto3" json:"parentTraceContext,omitempty"`
	// When true, the request fails with an ALREADY_EXISTS error if a workflow
	// instance with the same instanceId already exists, whether active or
	// completed. When false, an existing completed instance is restarted.
	EnforceUniqueInstanceId bool `protobuf:"varint,10,opt,name=enforceUniqueInstanceId,proto3" json:"enforceUniqueInstanceId,omitempty"`
	// router optionally routes this operation to the workflow instance owned
	// by another app. When targetAppID names a different app, the operation is
	// executed against that app's instance (same namespace unless
	// targetAppNamespace is set). sourceAppID is stamped by the sidecar, not
	// the client.
	Router        *TaskRouter `protobuf:"bytes,11,opt,name=router,proto3,oneof" json:"router,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInstanceRequest) Reset() {
	*x = CreateInstanceRequest{}
	mi := &file_orchestrator_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstanceRequest) ProtoMessage() {}

func (x *CreateInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstanceRequest.ProtoReflect.Descriptor instead.
func (*CreateInstanceRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *CreateInstanceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateInstanceRequest) GetVersion() *wrapperspb.StringValue {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *CreateInstanceRequest) GetInput() *wrapperspb.StringValue {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *CreateInstanceRequest) GetScheduledStartTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledStartTimestamp
	}
	return nil
}

func (x *CreateInstanceRequest) GetExecutionId() *wrapperspb.StringValue {
	if x != nil {
		return x.ExecutionId
	}
	return nil
}

func (x *CreateInstanceRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateInstanceRequest) GetParentTraceContext() *TraceContext {
	if x != nil {
		return x.ParentTraceContext
	}
	return nil
}

func (x *CreateInstanceRequest) GetEnforceUniqueInstanceId() bool {
	if x != nil {
		return x.EnforceUniqueInstanceId
	}
	return false
}

func (x *CreateInstanceRequest) GetRouter() *TaskRouter {
	if x != nil {
		return x.Router
	}
	return nil
}

type CreateInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInstanceResponse) Reset() {
	*x = CreateInstanceResponse{}
	mi := &file_orchestrator_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstanceResponse) ProtoMessage() {}

func (x *CreateInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstanceResponse.ProtoReflect.Descriptor instead.
func (*CreateInstanceResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateInstanceResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type GetInstanceRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	InstanceId          string                 `protobuf:"bytes,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	GetInputsAndOutputs bool                   `protobuf:"varint,2,opt,name=getInputsAndOutputs,proto3" json:"getInputsAndOutputs,omitempty"`
	// router optionally routes this operation to the workflow instance owned
	// by another app. sourceAppID is stamped by the sidecar, not the client.
	Router        *TaskRouter `protobuf:"bytes,3,opt,name=router,proto3,oneof" json:"router,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceRequest) Reset() {
	*x = GetInstanceRequest{}
	mi := &file_orchestrator_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceRequest) ProtoMessage() {}

func (x *GetInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceRequest.ProtoReflect.Descriptor instead.
func (*GetInstanceRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *GetInstanceRequest) GetGetInputsAndOutputs() bool {
	if x != nil {
		return x.GetInputsAndOutputs
	}
	return false
}

func (x *GetInstanceRequest) GetRouter() *TaskRouter {
	if x != nil {
		return x.Router
	}
	return nil
}

type GetInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	WorkflowState *WorkflowState         `protobuf:"bytes,2,opt,name=workflowState,proto3" json:"workflowState,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceResponse) Reset() {
	*x = GetInstanceResponse{}
	mi := &file_orchestrator_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceResponse) ProtoMessage() {}

func (x *GetInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceResponse.ProtoReflect.Descriptor instead.
func (*GetInstanceResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetInstanceResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *GetInstanceResponse) GetWorkflowState() *WorkflowState {
	if x != nil {
		return x.WorkflowState
	}
	return nil
}

type RaiseEventRequest struct {
	state      protoimpl.MessageState  `protogen:"open.v1"`
	InstanceId string                  `protobuf:"bytes,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	Name       string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Input      *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	// router optionally routes this operation to the workflow instance owned
	// by another app. sourceAppID is stamped by the sidecar, not the client.
	Router *TaskRouter `protobuf:"bytes,4,opt,name=router,proto3,oneof" json:"router,omitempty"`
	// externalDeliveryId identifies an at-least-once delivery from an external
	// publisher. Backends that support it durably accept a repeated value for
	// the same instance and event name without appending another event.
	ExternalDeliveryId *string `protobuf:"bytes,5,opt,name=externalDeliveryId,proto3,oneof" json:"externalDeliveryId,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RaiseEventRequest) Reset() {
	*x = RaiseEventRequest{}
	mi := &file_orchestrator_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaiseEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaiseEventRequest) ProtoMessage() {}

func (x *RaiseEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaiseEventRequest.ProtoReflect.Descriptor instead.
func (*RaiseEventRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_proto_rawDescGZIP(), []int{9}
}

func (x *RaiseEventRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RaiseEventRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RaiseEventRequest) GetInput() *wrapperspb.StringValue {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *RaiseEventRequest) GetRouter() *TaskRouter {
	if x != nil {
		return x.Router
	}
	return nil
}

func (x *RaiseEventRequest) GetExternalDeliveryId() string {
	if x != nil && x.ExternalDeliveryId != nil {
		return *x.ExternalDeliveryId
	}
	return ""
}

type RaiseEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaiseEventResponse) Reset() {
	*x = RaiseEventResponse{}
	mi := &file_orchestrator_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaiseEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaiseEventResponse) ProtoMessage() {}

func (x *RaiseEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaiseEventResponse.ProtoReflect.Descriptor instead.
func (*RaiseEventResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_proto_rawDescGZIP(), []int{10}
}

type TerminateRequest struct {
	state      protoimpl.MessageState  `protogen:"open.v1"`
	InstanceId string                  `protobuf:"bytes,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	Output     *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Recursive  bool                    `protobuf:"varint,3,opt,name=recursive,proto3" json:"recursive,omitempty"`
	// router optionally routes this operation to the workflow instance owned
	// by another app. sourceAppID is stamped by the sidecar, not the client.
	Router        *TaskRouter `protobuf:"bytes,4,opt,name=router,proto3,oneof" json:"router,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateRequest) Reset() {
	*x = TerminateRequest{}
	mi := &file_orchestrator_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateRequest) ProtoMessage() {}

func (x *TerminateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateRequest.ProtoReflect.Descriptor instead.
func (*TerminateRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_proto_rawDescGZIP(), []int{11}
}

func (x *TerminateRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *TerminateRequest) GetOutput() *wrapperspb.StringValue {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *TerminateRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *TerminateRequest) GetRouter() *TaskRouter {
	if x != nil {
		return x.Router
	}
	return nil
}

type TerminateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateResponse) Reset() {
	*x = TerminateResponse{}
	mi := &file_orchestrator_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateResponse) ProtoMessage() {}

func (x *TerminateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateResponse.ProtoReflect.Descriptor instead.
func (*TerminateResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_proto_rawDescGZIP(), []int{12}
}

type SuspendRequest struct {
	state      protoimpl.MessageState  `protogen:"open.v1"`
	InstanceId string                  `protobuf:"bytes,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	Reason     *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// router optionally routes this operation to the workflow instance owned
	// by another app. sourceAppID is stamped by the sidecar, not the client.
	Router        *TaskRouter `protobuf:"bytes,3,opt,name=router,proto3,oneof" json:"router,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendRequest) Reset() {
	*x = SuspendRequest{}
	mi := &file_orchestrator_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendRequest) ProtoMessage() {}

func (x *SuspendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendRequest.ProtoReflect.Descriptor instead.
func (*SuspendRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_proto_rawDescGZIP(), []int{13}
}

func (x *SuspendRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *SuspendRequest) GetReason() *wrapperspb.StringValue {
	if x != nil {
		return x.Reason
	}
	return nil
}

func (x *SuspendRequest) GetRouter() *TaskRouter {
	if x != nil {
		return x.Router
	}
	return nil
}

type SuspendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendResponse) Reset() {
	*x = SuspendResponse{}
	mi := &file_orchestrator_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendResponse) ProtoMessage() {}

func (x *SuspendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendResponse.ProtoReflect.Descriptor instead.
func (*SuspendResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_proto_rawDescGZIP(), []int{14}
}

type ResumeRequest struct {
	state      protoimpl.MessageState  `protogen:"open.v1"`
	InstanceId string                  `protobuf:"bytes,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	Reason     *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// router optionally routes this operation to the workflow instance owned
	// by another app. sourceAppID is stamped by the sidecar, not the client.
	Router        *TaskRouter `protobuf:"bytes,3,opt,name=router,proto3,oneof" json:"router,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRequest) Reset() {
	*x = ResumeRequest{}
	mi := &file_orchestrator_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRequest) ProtoMessage() {}

func (x *ResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRequest.ProtoReflect.Descriptor instead.
func (*ResumeRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_proto_rawDescGZIP(), []int{15}
}

func (x *ResumeRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ResumeRequest) GetReason() *wrapperspb.StringValue {
	if x != nil {
		return x.Reason
	}
	return nil
}

func (x *ResumeRequest) GetRouter() *TaskRouter {
	if x != nil {
		return x.Router
	}
	return nil
}

type ResumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeResponse) Reset() {
	*x = ResumeResponse{}
	mi := &file_orchestrator_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeResponse) ProtoMessage() {}

func (x *ResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeResponse.ProtoReflect.Descriptor instead.
func (*ResumeResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_proto_rawDescGZIP(), []int{16}
}

type PurgeInstancesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*PurgeInstancesRequest_InstanceId
	//	*PurgeInstancesRequest_PurgeInstanceFilter
	Request   isPurgeInstancesRequest_Request `protobuf_oneof:"request"`
	Recursive bool                            `protobuf:"varint,3,opt,name=recursive,proto3" json:"recursive,omitempty"`
	// force will force a purge of a workflow, regardless of its current
	// runtime state, or whether an active worker can process it, the backend
	// will attempt to delete it anyway. This neccessarily means the purging is
	// executed out side of the workflow state machine, and therefore, can lead
	// to corrupt state or broken workflow execution. Usage of this should
	// _only_ be used when the client knows the workflow is not being currently
	// processed. It is highly recommended to avoid using this flag unless
	// absolutely necessary.
	// Defaults to false.
	Force *bool `protobuf:"varint,4,opt,name=force,proto3,oneof" json:"force,omitempty"`
	// router optionally routes this operation to the workflow instance owned
	// by another app. Cross-app purges are delegated to the target app in
	// full, so they are always recursive on the remote side. sourceAppID is
	// stamped by the sidecar, not the client.
	Router        *TaskRouter `protobuf:"bytes,5,opt,name=router,proto3,oneof" json:"router,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeInstancesRequest) Reset() {
	*x = PurgeInstancesRequest{}
	mi := &file_orchestrator_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeInstancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeInstancesRequest) ProtoMessage() {}

func (x *PurgeInstancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeInstancesRequest.ProtoReflect.Descriptor instead.
func (*PurgeInstancesRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_proto_rawDescGZIP(), []int{17}
}

func (x *PurgeInstancesRequest) GetRequest() isPurgeInstancesRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *PurgeInstancesRequest) GetInstanceId() string {
	if x != nil {
		if x, ok := x.Request.(*PurgeInstancesRequest_InstanceId); ok {
			return x.InstanceId
		}
	}
	return ""
}

func (x *PurgeInstancesRequest) GetPurgeInstanceFilter() *PurgeInstanceFilter {
	if x != nil {
		if x, ok := x.Request.(*PurgeInstancesRequest_PurgeInstanceFilter); ok {
			return x.PurgeInstanceFilter
		}
	}
	return nil
}

func (x *PurgeInstancesRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *PurgeInstancesRequest) GetForce() bool {
	if x != nil && x.Force != nil {
		return *x.Force
	}
	return false
}

func (x *PurgeInstancesRequest) GetRouter() *TaskRouter {
	if x != nil {
		return x.Router
	}
	return nil
}

type isPurgeInstancesRequest_Request interface {
	isPurgeInstancesRequest_Request()
}

type PurgeInstancesRequest_InstanceId struct {
	InstanceId string `protobuf:"bytes,1,opt,name=instanceId,proto3,oneof"`
}

type PurgeInstancesRequest_PurgeInstanceFilter struct {
	PurgeInstanceFilter *PurgeInstanceFilter `protobuf:"bytes,2,opt,name=purgeInstanceFilter,proto3,oneof"`
}

func (*PurgeInstancesRequest_InstanceId) isPurgeInstancesRequest_Request() {}

func (*PurgeInstancesRequest_PurgeInstanceFilter) isPurgeInstancesRequest_Request() {}

type PurgeInstanceFilter struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CreatedTimeFrom *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=createdTimeFrom,proto3" json:"createdTimeFrom,omitempty"`
	CreatedTimeTo   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=createdTimeTo,proto3" json:"createdTimeTo,omitempty"`
	RuntimeStatus   []OrchestrationStatus  `protobuf:"varint,3,rep,packed,name=runtimeStatus,proto3,enum=OrchestrationStatus" json:"runtimeStatus,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PurgeInstanceFilter) Reset() {
	*x = PurgeInstanceFilter{}
	mi := &file_orchestrator_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeInstanceFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeInstanceFilter) ProtoMessage() {}

func (x *PurgeInstanceFilter) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeInstanceFilter.ProtoReflect.Descriptor instead.
func (*PurgeInstanceFilter) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_proto_rawDescGZIP(), []int{18}
}

func (x *PurgeInstanceFilter) GetCreatedTimeFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTimeFrom
	}
	return nil
}

func (x *PurgeInstanceFilter) GetCreatedTimeTo() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTimeTo
	}
	return nil
}

func (x *PurgeInstanceFilter) GetRuntimeStatus() []OrchestrationStatus {
	if x != nil {
		return x.RuntimeStatus
	}
	return nil
}

type PurgeInstancesResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	DeletedInstanceCount int32                  `protobuf:"varint,1,opt,name=deletedInstanceCount,proto3" json:"deletedInstanceCount,omitempty"`
	IsComplete           *wrapperspb.BoolValue  `protobuf:"bytes,2,opt,name=isComplete,proto3" json:"isComplete,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PurgeInstancesResponse) Reset() {
	*x = PurgeInstancesResponse{}
	mi := &file_orchestrator_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeInstancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeInstancesResponse) ProtoMessage() {}

func (x *PurgeInstancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeInstancesResponse.ProtoReflect.Descriptor instead.
func (*PurgeInstancesResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_proto_rawDescGZIP(), []int{19}
}

func (x *PurgeInstancesResponse) GetDeletedInstanceCount() int32 {
	if x != nil {
		return x.DeletedInstanceCount
	}
	return 0
}

func (x *PurgeInstancesResponse) GetIsComplete() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsComplete
	}
	return nil
}

type GetWorkItemsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// capabilities advertises the optional protocol features this worker
	// supports, so the service can opt into optimizations on a per-stream
	// basis. Workers that leave this empty receive the default (fully
	// self-contained) behavior.
	Capabilities  []WorkerCapability `protobuf:"varint,4,rep,packed,name=capabilities,proto3,enum=WorkerCapability" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkItemsRequest) Reset() {
	*x = GetWorkItemsRequest{}
	mi := &file_orchestrator_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkItemsRequest) ProtoMessage() {}

func (x *GetWorkItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkItemsRequest.ProtoReflect.Descriptor instead.
func (*GetWorkItemsRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_proto_rawDescGZIP(), []int{20}
}

func (x *GetWorkItemsRequest) GetCapabilities() []WorkerCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type WorkItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*WorkItem_WorkflowRequest
	//	*WorkItem_ActivityRequest
	Request         isWorkItem_Request `protobuf_oneof:"request"`
	CompletionToken string             `protobuf:"bytes,10,opt,name=completionToken,proto3" json:"completionToken,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkItem) Reset() {
	*x = WorkItem{}
	mi := &file_orchestrator_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkItem) ProtoMessage() {}

func (x *WorkItem) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkItem.ProtoReflect.Descriptor instead.
func (*WorkItem) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_proto_rawDescGZIP(), []int{21}
}

func (x *WorkItem) GetRequest() isWorkItem_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *WorkItem) GetWorkflowRequest() *WorkflowRequest {
	if x != nil {
		if x, ok := x.Request.(*WorkItem_WorkflowRequest); ok {
			return x.WorkflowRequest
		}
	}
	return nil
}

func (x *WorkItem) GetActivityRequest() *ActivityRequest {
	if x != nil {
		if x, ok := x.Request.(*WorkItem_ActivityRequest); ok {
			return x.ActivityRequest
		}
	}
	return nil
}

func (x *WorkItem) GetCompletionToken() string {
	if x != nil {
		return x.CompletionToken
	}
	return ""
}

type isWorkItem_Request interface {
	isWorkItem_Request()
}

type WorkItem_WorkflowRequest struct {
	WorkflowRequest *WorkflowRequest `protobuf:"bytes,1,opt,name=workflowRequest,proto3,oneof"`
}

type WorkItem_ActivityRequest struct {
	ActivityRequest *ActivityRequest `protobuf:"bytes,2,opt,name=activityRequest,proto3,oneof"`
}

func (*WorkItem_WorkflowRequest) isWorkItem_Request() {}

func (*WorkItem_ActivityRequest) isWorkItem_Request() {}

type CompleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTaskResponse) Reset() {
	*x = CompleteTaskResponse{}
	mi := &file_orchestrator_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTaskResponse) ProtoMessage() {}

func (x *CompleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTaskResponse.ProtoReflect.Descriptor instead.
func (*CompleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_proto_rawDescGZIP(), []int{22}
}

// ListInstanceIDsRequest is used to list all workflow instances.
type ListInstanceIDsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// continuationToken is the continuation token to use for pagination. This
	// is the token which the next page should start from. If not given, the
	// first page will be returned.
	ContinuationToken *string `protobuf:"bytes,1,opt,name=continuationToken,proto3,oneof" json:"continuationToken,omitempty"`
	// pageSize is the maximum number of instances to return for this page. If
	// not given, all instances will be attempted to be returned.
	PageSize      *uint32 `protobuf:"varint,2,opt,name=pageSize,proto3,oneof" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstanceIDsRequest) Reset() {
	*x = ListInstanceIDsRequest{}
	mi := &file_orchestrator_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstanceIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstanceIDsRequest) ProtoMessage() {}

func (x *ListInstanceIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstanceIDsRequest.ProtoReflect.Descriptor instead.
func (*ListInstanceIDsRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_proto_rawDescGZIP(), []int{23}
}

func (x *ListInstanceIDsRequest) GetContinuationToken() string {
	if x != nil && x.ContinuationToken != nil {
		return *x.ContinuationToken
	}
	return ""
}

func (x *ListInstanceIDsRequest) GetPageSize() uint32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

// ListInstanceIDsResponse is the response to executing ListInstanceIDs.
type ListInstanceIDsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// instanceIds is the list of instance IDs returned.
	InstanceIds []string `protobuf:"bytes,1,rep,name=instanceIds,proto3" json:"instanceIds,omitempty"`
	// continuationToken is the continuation token to use for pagination. If
	// there are no more pages, this will be null.
	ContinuationToken *string `protobuf:"bytes,2,opt,name=continuationToken,proto3,oneof" json:"continuationToken,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListInstanceIDsResponse) Reset() {
	*x = ListInstanceIDsResponse{}
	mi := &file_orchestrator_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstanceIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstanceIDsResponse) ProtoMessage() {}

func (x *ListInstanceIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstanceIDsResponse.ProtoReflect.Descriptor instead.
func (*ListInstanceIDsResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_proto_rawDescGZIP(), []int{24}
}

func (x *ListInstanceIDsResponse) GetInstanceIds() []string {
	if x != nil {
		return x.InstanceIds
	}
	return nil
}

func (x *ListInstanceIDsResponse) GetContinuationToken() string {
	if x != nil && x.ContinuationToken != nil {
		return *x.ContinuationToken
	}
	return ""
}

// GetInstanceHistoryRequest is used to get the full history of a
// workflow instance.
type GetInstanceHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceHistoryRequest) Reset() {
	*x = GetInstanceHistoryRequest{}
	mi := &file_orchestrator_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceHistoryRequest) ProtoMessage() {}

func (x *GetInstanceHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetInstanceHistoryRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_proto_rawDescGZIP(), []int{25}
}

func (x *GetInstanceHistoryRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

// GetInstanceHistoryResponse is the response to executing GetInstanceHistory.
type GetInstanceHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*HistoryEvent        `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceHistoryResponse) Reset() {
	*x = GetInstanceHistoryResponse{}
	mi := &file_orchestrator_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceHistoryResponse) ProtoMessage() {}

func (x *GetInstanceHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetInstanceHistoryResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_proto_rawDescGZIP(), []int{26}
}

func (x *GetInstanceHistoryResponse) GetEvents() []*HistoryEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_orchestrator_service_proto protoreflect.FileDescriptor

const file_orchestrator_service_proto_rawDesc = "" +
	"\n" +
	"\x1aorchestrator_service.proto\x1a\x13orchestration.proto\x1a\x14history_events.proto\x1a\x1aorchestrator_actions.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xae\x03\n" +
	"\x0fActivityRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x126\n" +
	"\aversion\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\aversion\x122\n" +
	"\x05input\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x05input\x12=\n" +
	"\x10workflowInstance\x18\x04 \x01(\v2\x11.WorkflowInstanceR\x10workflowInstance\x12\x16\n" +
	"\x06taskId\x18\x05 \x01(\x05R\x06taskId\x12=\n" +
	"\x12parentTraceContext\x18\x06 \x01(\v2\r.TraceContextR\x12parentTraceContext\x12(\n" +
	"\x0ftaskExecutionId\x18\a \x01(\tR\x0ftaskExecutionId\x12E\n" +
	"\x11propagatedHistory\x18\b \x01(\v2\x12.PropagatedHistoryH\x00R\x11propagatedHistory\x88\x01\x01B\x14\n" +
	"\x12_propagatedHistory\"\xe7\x01\n" +
	"\x10ActivityResponse\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06taskId\x18\x02 \x01(\x05R\x06taskId\x124\n" +
	"\x06result\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x06result\x12;\n" +
	"\x0efailureDetails\x18\x04 \x01(\v2\x13.TaskFailureDetailsR\x0efailureDetails\x12(\n" +
	"\x0fcompletionToken\x18\x05 \x01(\tR\x0fcompletionToken\"/\n" +
	"\rCachedHistory\x12\x1e\n" +
	"\n" +
	"eventCount\x18\x01 \x01(\x05R\n" +
	"eventCount\"\xee\x03\n" +
	"\x0fWorkflowRequest\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x01 \x01(\tR\n" +
	"instanceId\x12>\n" +
	"\vexecutionId\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\vexecutionId\x12-\n" +
	"\n" +
	"pastEvents\x18\x03 \x03(\v2\r.HistoryEventR\n" +
	"pastEvents\x12+\n" +
	"\tnewEvents\x18\x04 \x03(\v2\r.HistoryEventR\tnewEvents\x12:\n" +
	"\x18requiresHistoryStreaming\x18\x06 \x01(\bR\x18requiresHistoryStreaming\x12(\n" +
	"\x06router\x18\a \x01(\v2\v.TaskRouterH\x00R\x06router\x88\x01\x01\x12E\n" +
	"\x11propagatedHistory\x18\b \x01(\v2\x12.PropagatedHistoryH\x01R\x11propagatedHistory\x88\x01\x01\x129\n" +
	"\rcachedHistory\x18\t \x01(\v2\x0e.CachedHistoryH\x02R\rcachedHistory\x88\x01\x01B\t\n" +
	"\a_routerB\x14\n" +
	"\x12_propagatedHistoryB\x10\n" +
	"\x0e_cachedHistoryJ\x04\b\x05\x10\x06\"\xd3\x02\n" +
	"\x10WorkflowResponse\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x01 \x01(\tR\n" +
	"instanceId\x12)\n" +
	"\aactions\x18\x02 \x03(\v2\x0f.WorkflowActionR\aactions\x12@\n" +
	"\fcustomStatus\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\fcustomStatus\x12(\n" +
	"\x0fcompletionToken\x18\x04 \x01(\tR\x0fcompletionToken\x12K\n" +
	"\x12numEventsProcessed\x18\x05 \x01(\v2\x1b.google.protobuf.Int32ValueR\x12numEventsProcessed\x12/\n" +
	"\aversion\x18\x06 \x01(\v2\x10.WorkflowVersionH\x00R\aversion\x88\x01\x01B\n" +
	"\n" +
	"\b_version\"\x8c\x05\n" +
	"\x15CreateInstanceRequest\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x126\n" +
	"\aversion\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\aversion\x122\n" +
	"\x05input\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x05input\x12T\n" +
	"\x17scheduledStartTimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x17scheduledStartTimestamp\x12>\n" +
	"\vexecutionId\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\vexecutionId\x124\n" +
	"\x04tags\x18\b \x03(\v2 .CreateInstanceRequest.TagsEntryR\x04tags\x12=\n" +
	"\x12parentTraceContext\x18\t \x01(\v2\r.TraceContextR\x12parentTraceContext\x128\n" +
	"\x17enforceUniqueInstanceId\x18\n" +
	" \x01(\bR\x17enforceUniqueInstanceId\x12(\n" +
	"\x06router\x18\v \x01(\v2\v.TaskRouterH\x00R\x06router\x88\x01\x01\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\a_routerJ\x04\b\x06\x10\aR\x1aorchestrationIdReusePolicy\"8\n" +
	"\x16CreateInstanceResponse\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x01 \x01(\tR\n" +
	"instanceId\"\x9b\x01\n" +
	"\x12GetInstanceRequest\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x01 \x01(\tR\n" +
	"instanceId\x120\n" +
	"\x13getInputsAndOutputs\x18\x02 \x01(\bR\x13getInputsAndOutputs\x12(\n" +
	"\x06router\x18\x03 \x01(\v2\v.TaskRouterH\x00R\x06router\x88\x01\x01B\t\n" +
	"\a_router\"c\n" +
	"\x13GetInstanceResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x124\n" +
	"\rworkflowState\x18\x02 \x01(\v2\x0e.WorkflowStateR\rworkflowState\"\xfc\x01\n" +
	"\x11RaiseEventRequest\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x122\n" +
	"\x05input\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x05input\x12(\n" +
	"\x06router\x18\x04 \x01(\v2\v.TaskRouterH\x00R\x06router\x88\x01\x01\x123\n" +
	"\x12externalDeliveryId\x18\x05 \x01(\tH\x01R\x12externalDeliveryId\x88\x01\x01B\t\n" +
	"\a_routerB\x15\n" +
	"\x13_externalDeliveryId\"\x14\n" +
	"\x12RaiseEventResponse\"\xbb\x01\n" +
	"\x10TerminateRequest\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x01 \x01(\tR\n" +
	"instanceId\x124\n" +
	"\x06output\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x06output\x12\x1c\n" +
	"\trecursive\x18\x03 \x01(\bR\trecursive\x12(\n" +
	"\x06router\x18\x04 \x01(\v2\v.TaskRouterH\x00R\x06router\x88\x01\x01B\t\n" +
	"\a_router\"\x13\n" +
	"\x11TerminateResponse\"\x9b\x01\n" +
	"\x0eSuspendRequest\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x01 \x01(\tR\n" +
	"instanceId\x124\n" +
	"\x06reason\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x06reason\x12(\n" +
	"\x06router\x18\x03 \x01(\v2\v.TaskRouterH\x00R\x06router\x88\x01\x01B\t\n" +
	"\a_router\"\x11\n" +
	"\x0fSuspendResponse\"\x9a\x01\n" +
	"\rResumeRequest\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x01 \x01(\tR\n" +
	"instanceId\x124\n" +
	"\x06reason\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x06reason\x12(\n" +
	"\x06router\x18\x03 \x01(\v2\v.TaskRouterH\x00R\x06router\x88\x01\x01B\t\n" +
	"\a_router\"\x10\n" +
	"\x0eResumeResponse\"\x86\x02\n" +
	"\x15PurgeInstancesRequest\x12 \n" +
	"\n" +
	"instanceId\x18\x01 \x01(\tH\x00R\n" +
	"instanceId\x12H\n" +
	"\x13purgeInstanceFilter\x18\x02 \x01(\v2\x14.PurgeInstanceFilterH\x00R\x13purgeInstanceFilter\x12\x1c\n" +
	"\trecursive\x18\x03 \x01(\bR\trecursive\x12\x19\n" +
	"\x05force\x18\x04 \x01(\bH\x01R\x05force\x88\x01\x01\x12(\n" +
	"\x06router\x18\x05 \x01(\v2\v.TaskRouterH\x02R\x06router\x88\x01\x01B\t\n" +
	"\arequestB\b\n" +
	"\x06_forceB\t\n" +
	"\a_router\"\xd9\x01\n" +
	"\x13PurgeInstanceFilter\x12D\n" +
	"\x0fcreatedTimeFrom\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x0fcreatedTimeFrom\x12@\n" +
	"\rcreatedTimeTo\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\rcreatedTimeTo\x12:\n" +
	"\rruntimeStatus\x18\x03 \x03(\x0e2\x14.OrchestrationStatusR\rruntimeStatus\"\x88\x01\n" +
	"\x16PurgeInstancesResponse\x122\n" +
	"\x14deletedInstanceCount\x18\x01 \x01(\x05R\x14deletedInstanceCount\x12:\n" +
	"\n" +
	"isComplete\x18\x02 \x01(\v2\x1a.google.protobuf.BoolValueR\n" +
	"isComplete\"d\n" +
	"\x13GetWorkItemsRequest\x125\n" +
	"\fcapabilities\x18\x04 \x03(\x0e2\x11.WorkerCapabilityR\fcapabilitiesJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\n" +
	"\x10\v\"\xcd\x01\n" +
	"\bWorkItem\x12<\n" +
	"\x0fworkflowRequest\x18\x01 \x01(\v2\x10.WorkflowRequestH\x00R\x0fworkflowRequest\x12<\n" +
	"\x0factivityRequest\x18\x02 \x01(\v2\x10.ActivityRequestH\x00R\x0factivityRequest\x12(\n" +
	"\x0fcompletionToken\x18\n" +
	" \x01(\tR\x0fcompletionTokenB\t\n" +
	"\arequestJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06\"\x16\n" +
	"\x14CompleteTaskResponse\"\x8f\x01\n" +
	"\x16ListInstanceIDsRequest\x121\n" +
	"\x11continuationToken\x18\x01 \x01(\tH\x00R\x11continuationToken\x88\x01\x01\x12\x1f\n" +
	"\bpageSize\x18\x02 \x01(\rH\x01R\bpageSize\x88\x01\x01B\x14\n" +
	"\x12_continuationTokenB\v\n" +
	"\t_pageSize\"\x84\x01\n" +
	"\x17ListInstanceIDsResponse\x12 \n" +
	"\vinstanceIds\x18\x01 \x03(\tR\vinstanceIds\x121\n" +
	"\x11continuationToken\x18\x02 \x01(\tH\x00R\x11continuationToken\x88\x01\x01B\x14\n" +
	"\x12_continuationToken\";\n" +
	"\x19GetInstanceHistoryRequest\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x01 \x01(\tR\n" +
	"instanceId\"C\n" +
	"\x1aGetInstanceHistoryResponse\x12%\n" +
	"\x06events\x18\x01 \x03(\v2\r.HistoryEventR\x06events*\x88\x01\n" +
	"\x10WorkerCapability\x12!\n" +
	"\x1dWORKER_CAPABILITY_UNSPECIFIED\x10\x00\x12&\n" +
	"\"WORKER_CAPABILITY_STATEFUL_HISTORY\x10\x02\"\x04\b\x01\x10\x01*#WORKER_CAPABILITY_HISTORY_STREAMING2\x8d\b\n" +
	"\x15TaskHubSidecarService\x127\n" +
	"\x05Hello\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\rStartInstance\x12\x16.CreateInstanceRequest\x1a\x17.CreateInstanceResponse\x128\n" +
	"\vGetInstance\x12\x13.GetInstanceRequest\x1a\x14.GetInstanceResponse\x12A\n" +
	"\x14WaitForInstanceStart\x12\x13.GetInstanceRequest\x1a\x14.GetInstanceResponse\x12F\n" +
	"\x19WaitForInstanceCompletion\x12\x13.GetInstanceRequest\x1a\x14.GetInstanceResponse\x125\n" +
	"\n" +
	"RaiseEvent\x12\x12.RaiseEventRequest\x1a\x13.RaiseEventResponse\x12:\n" +
	"\x11TerminateInstance\x12\x11.TerminateRequest\x1a\x12.TerminateResponse\x124\n" +
	"\x0fSuspendInstance\x12\x0f.SuspendRequest\x1a\x10.SuspendResponse\x121\n" +
	"\x0eResumeInstance\x12\x0e.ResumeRequest\x1a\x0f.ResumeResponse\x12A\n" +
	"\x0ePurgeInstances\x12\x16.PurgeInstancesRequest\x1a\x17.PurgeInstancesResponse\x121\n" +
	"\fGetWorkItems\x12\x14.GetWorkItemsRequest\x1a\t.WorkItem0\x01\x12@\n" +
	"\x14CompleteActivityTask\x12\x11.ActivityResponse\x1a\x15.CompleteTaskResponse\x12I\n" +
	"\x18CompleteOrchestratorTask\x12\x11.WorkflowResponse\x1a\x15.CompleteTaskResponse\"\x03\x88\x02\x01\x12@\n" +
	"\x14CompleteWorkflowTask\x12\x11.WorkflowResponse\x1a\x15.CompleteTaskResponse\x12D\n" +
	"\x0fListInstanceIDs\x12\x17.ListInstanceIDsRequest\x1a\x18.ListInstanceIDsResponse\x12M\n" +
	"\x12GetInstanceHistory\x12\x1a.GetInstanceHistoryRequest\x1a\x1b.GetInstanceHistoryResponseBV\n" +
	"+io.dapr.durabletask.implementation.protobufZ\v/api/protos\xaa\x02\x19Dapr.DurableTask.Protobufb\x06proto3"

var (
	file_orchestrator_service_proto_rawDescOnce sync.Once
	file_orchestrator_service_proto_rawDescData []byte
)

func file_orchestrator_service_proto_rawDescGZIP() []byte {
	file_orchestrator_service_proto_rawDescOnce.Do(func() {
		file_orchestrator_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestrator_service_proto_rawDesc), len(file_orchestrator_service_proto_rawDesc)))
	})
	return file_orchestrator_service_proto_rawDescData
}

var file_orchestrator_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_orchestrator_service_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_orchestrator_service_proto_goTypes = []any{
	(WorkerCapability)(0),              // 0: WorkerCapability
	(*ActivityRequest)(nil),            // 1: ActivityRequest
	(*ActivityResponse)(nil),           // 2: ActivityResponse
	(*CachedHistory)(nil),              // 3: CachedHistory
	(*WorkflowRequest)(nil),            // 4: WorkflowRequest
	(*WorkflowResponse)(nil),           // 5: WorkflowResponse
	(*CreateInstanceRequest)(nil),      // 6: CreateInstanceRequest
	(*CreateInstanceResponse)(nil),     // 7: CreateInstanceResponse
	(*GetInstanceRequest)(nil),         // 8: GetInstanceRequest
	(*GetInstanceResponse)(nil),        // 9: GetInstanceResponse
	(*RaiseEventRequest)(nil),          // 10: RaiseEventRequest
	(*RaiseEventResponse)(nil),         // 11: RaiseEventResponse
	(*TerminateRequest)(nil),           // 12: TerminateRequest
	(*TerminateResponse)(nil),          // 13: TerminateResponse
	(*SuspendRequest)(nil),             // 14: SuspendRequest
	(*SuspendResponse)(nil),            // 15: SuspendResponse
	(*ResumeRequest)(nil),              // 16: ResumeRequest
	(*ResumeResponse)(nil),             // 17: ResumeResponse
	(*PurgeInstancesRequest)(nil),      // 18: PurgeInstancesRequest
	(*PurgeInstanceFilter)(nil),        // 19: PurgeInstanceFilter
	(*PurgeInstancesResponse)(nil),     // 20: PurgeInstancesResponse
	(*GetWorkItemsRequest)(nil),        // 21: GetWorkItemsRequest
	(*WorkItem)(nil),                   // 22: WorkItem
	(*CompleteTaskResponse)(nil),       // 23: CompleteTaskResponse
	(*ListInstanceIDsRequest)(nil),     // 24: ListInstanceIDsRequest
	(*ListInstanceIDsResponse)(nil),    // 25: ListInstanceIDsResponse
	(*GetInstanceHistoryRequest)(nil),  // 26: GetInstanceHistoryRequest
	(*GetInstanceHistoryResponse)(nil), // 27: GetInstanceHistoryResponse
	nil,                                // 28: CreateInstanceRequest.TagsEntry
	(*wrapperspb.StringValue)(nil),     // 29: google.protobuf.StringValue
	(*WorkflowInstance)(nil),           // 30: WorkflowInstance
	(*TraceContext)(nil),               // 31: TraceContext
	(*PropagatedHistory)(nil),          // 32: PropagatedHistory
	(*TaskFailureDetails)(nil),         // 33: TaskFailureDetails
	(*HistoryEvent)(nil),               // 34: HistoryEvent
	(*TaskRouter)(nil),                 // 35: TaskRouter
	(*WorkflowAction)(nil),             // 36: WorkflowAction
	(*wrapperspb.Int32Value)(nil),      // 37: google.protobuf.Int32Value
	(*WorkflowVersion)(nil),            // 38: WorkflowVersion
	(*timestamppb.Timestamp)(nil),      // 39: google.protobuf.Timestamp
	(*WorkflowState)(nil),              // 40: WorkflowState
	(OrchestrationStatus)(0),           // 41: OrchestrationStatus
	(*wrapperspb.BoolValue)(nil),       // 42: google.protobuf.BoolValue
	(*emptypb.Empty)(nil),              // 43: google.protobuf.Empty
}
var file_orchestrator_service_proto_depIdxs = []int32{
	29, // 0: ActivityRequest.version:type_name -> google.protobuf.StringValue
	29, // 1: ActivityRequest.input:type_name -> google.protobuf.StringValue
	30, // 2: ActivityRequest.workflowInstance:type_name -> WorkflowInstance
	31, // 3: ActivityRequest.parentTraceContext:type_name -> TraceContext
	32, // 4: ActivityRequest.propagatedHistory:type_name -> PropagatedHistory
	29, // 5: ActivityResponse.result:type_name -> google.protobuf.StringValue
	33, // 6: ActivityResponse.failureDetails:type_name -> TaskFailureDetails
	29, // 7: WorkflowRequest.executionId:type_name -> google.protobuf.StringValue
	34, // 8: WorkflowRequest.pastEvents:type_name -> HistoryEvent
	34, // 9: WorkflowRequest.newEvents:type_name -> HistoryEvent
	35, // 10: WorkflowRequest.router:type_name -> TaskRouter
	32, // 11: WorkflowRequest.propagatedHistory:type_name -> PropagatedHistory
	3,  // 12: WorkflowRequest.cachedHistory:type_name -> CachedHistory
	36, // 13: WorkflowResponse.actions:type_name -> WorkflowAction
	29, // 14: WorkflowResponse.customStatus:type_name -> google.protobuf.StringValue
	37, // 15: WorkflowResponse.numEventsProcessed:type_name -> google.protobuf.Int32Value
	38, // 16: WorkflowResponse.version:type_name -> WorkflowVersion
	29, // 17: CreateInstanceRequest.version:type_name -> google.protobuf.StringValue
	29, // 18: CreateInstanceRequest.input:type_name -> google.protobuf.StringValue
	39, // 19: CreateInstanceRequest.scheduledStartTimestamp:type_name -> google.protobuf.Timestamp
	29, // 20: CreateInstanceRequest.executionId:type_name -> google.protobuf.StringValue
	28, // 21: CreateInstanceRequest.tags:type_name -> CreateInstanceRequest.TagsEntry
	31, // 22: CreateInstanceRequest.parentTraceContext:type_name -> TraceContext
	35, // 23: CreateInstanceRequest.router:type_name -> TaskRouter
	35, // 24: GetInstanceRequest.router:type_name -> TaskRouter
	40, // 25: GetInstanceResponse.workflowState:type_name -> WorkflowState
	29, // 26: RaiseEventRequest.input:type_name -> google.protobuf.StringValue
	35, // 27: RaiseEventRequest.router:type_name -> TaskRouter
	29, // 28: TerminateRequest.output:type_name -> google.protobuf.StringValue
	35, // 29: TerminateRequest.router:type_name -> TaskRouter
	29, // 30: SuspendRequest.reason:type_name -> google.protobuf.StringValue
	35, // 31: SuspendRequest.router:type_name -> TaskRouter
	29, // 32: ResumeRequest.reason:type_name -> google.protobuf.StringValue
	35, // 33: ResumeRequest.router:type_name -> TaskRouter
	19, // 34: PurgeInstancesRequest.purgeInstanceFilter:type_name -> PurgeInstanceFilter
	35, // 35: PurgeInstancesRequest.router:type_name -> TaskRouter
	39, // 36: PurgeInstanceFilter.createdTimeFrom:type_name -> google.protobuf.Timestamp
	39, // 37: PurgeInstanceFilter.createdTimeTo:type_name -> google.protobuf.Timestamp
	41, // 38: PurgeInstanceFilter.runtimeStatus:type_name -> OrchestrationStatus
	42, // 39: PurgeInstancesResponse.isComplete:type_name -> google.protobuf.BoolValue
	0,  // 40: GetWorkItemsRequest.capabilities:type_name -> WorkerCapability
	4,  // 41: WorkItem.workflowRequest:type_name -> WorkflowRequest
	1,  // 42: WorkItem.activityRequest:type_name -> ActivityRequest
	34, // 43: GetInstanceHistoryResponse.events:type_name -> HistoryEvent
	43, // 44: TaskHubSidecarService.Hello:input_type -> google.protobuf.Empty
	6,  // 45: TaskHubSidecarService.StartInstance:input_type -> CreateInstanceRequest
	8,  // 46: TaskHubSidecarService.GetInstance:input_type -> GetInstanceRequest
	8,  // 47: TaskHubSidecarService.WaitForInstanceStart:input_type -> GetInstanceRequest
	8,  // 48: TaskHubSidecarService.WaitForInstanceCompletion:input_type -> GetInstanceRequest
	10, // 49: TaskHubSidecarService.RaiseEvent:input_type -> RaiseEventRequest
	12, // 50: TaskHubSidecarService.TerminateInstance:input_type -> TerminateRequest
	14, // 51: TaskHubSidecarService.SuspendInstance:input_type -> SuspendRequest
	16, // 52: TaskHubSidecarService.ResumeInstance:input_type -> ResumeRequest
	18, // 53: TaskHubSidecarService.PurgeInstances:input_type -> PurgeInstancesRequest
	21, // 54: TaskHubSidecarService.GetWorkItems:input_type -> GetWorkItemsRequest
	2,  // 55: TaskHubSidecarService.CompleteActivityTask:input_type -> ActivityResponse
	5,  // 56: TaskHubSidecarService.CompleteOrchestratorTask:input_type -> WorkflowResponse
	5,  // 57: TaskHubSidecarService.CompleteWorkflowTask:input_type -> WorkflowResponse
	24, // 58: TaskHubSidecarService.ListInstanceIDs:input_type -> ListInstanceIDsRequest
	26, // 59: TaskHubSidecarService.GetInstanceHistory:input_type -> GetInstanceHistoryRequest
	43, // 60: TaskHubSidecarService.Hello:output_type -> google.protobuf.Empty
	7,  // 61: TaskHubSidecarService.StartInstance:output_type -> CreateInstanceResponse
	9,  // 62: TaskHubSidecarService.GetInstance:output_type -> GetInstanceResponse
	9,  // 63: TaskHubSidecarService.WaitForInstanceStart:output_type -> GetInstanceResponse
	9,  // 64: TaskHubSidecarService.WaitForInstanceCompletion:output_type -> GetInstanceResponse
	11, // 65: TaskHubSidecarService.RaiseEvent:output_type -> RaiseEventResponse
	13, // 66: TaskHubSidecarService.TerminateInstance:output_type -> TerminateResponse
	15, // 67: TaskHubSidecarService.SuspendInstance:output_type -> SuspendResponse
	17, // 68: TaskHubSidecarService.ResumeInstance:output_type -> ResumeResponse
	20, // 69: TaskHubSidecarService.PurgeInstances:output_type -> PurgeInstancesResponse
	22, // 70: TaskHubSidecarService.GetWorkItems:output_type -> WorkItem
	23, // 71: TaskHubSidecarService.CompleteActivityTask:output_type -> CompleteTaskResponse
	23, // 72: TaskHubSidecarService.CompleteOrchestratorTask:output_type -> CompleteTaskResponse
	23, // 73: TaskHubSidecarService.CompleteWorkflowTask:output_type -> CompleteTaskResponse
	25, // 74: TaskHubSidecarService.ListInstanceIDs:output_type -> ListInstanceIDsResponse
	27, // 75: TaskHubSidecarService.GetInstanceHistory:output_type -> GetInstanceHistoryResponse
	60, // [60:76] is the sub-list for method output_type
	44, // [44:60] is the sub-list for method input_type
	44, // [44:44] is the sub-list for extension type_name
	44, // [44:44] is the sub-list for extension extendee
	0,  // [0:44] is the sub-list for field type_name
}

func init() { file_orchestrator_service_proto_init() }
func file_orchestrator_service_proto_init() {
	if File_orchestrator_service_proto != nil {
		return
	}
	file_orchestration_proto_init()
	file_history_events_proto_init()
	file_orchestrator_actions_proto_init()
	file_orchestrator_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_orchestrator_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_orchestrator_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_orchestrator_service_proto_msgTypes[5].OneofWrappers = []any{}
	file_orchestrator_service_proto_msgTypes[7].OneofWrappers = []any{}
	file_orchestrator_service_proto_msgTypes[9].OneofWrappers = []any{}
	file_orchestrator_service_proto_msgTypes[11].OneofWrappers = []any{}
	file_orchestrator_service_proto_msgTypes[13].OneofWrappers = []any{}
	file_orchestrator_service_proto_msgTypes[15].OneofWrappers = []any{}
	file_orchestrator_service_proto_msgTypes[17].OneofWrappers = []any{
		(*PurgeInstancesRequest_InstanceId)(nil),
		(*PurgeInstancesRequest_PurgeInstanceFilter)(nil),
	}
	file_orchestrator_service_proto_msgTypes[21].OneofWrappers = []any{
		(*WorkItem_WorkflowRequest)(nil),
		(*WorkItem_ActivityRequest)(nil),
	}
	file_orchestrator_service_proto_msgTypes[23].OneofWrappers = []any{}
	file_orchestrator_service_proto_msgTypes[24].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestrator_service_proto_rawDesc), len(file_orchestrator_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchestrator_service_proto_goTypes,
		DependencyIndexes: file_orchestrator_service_proto_depIdxs,
		EnumInfos:         file_orchestrator_service_proto_enumTypes,
		MessageInfos:      file_orchestrator_service_proto_msgTypes,
	}.Build()
	File_orchestrator_service_proto = out.File
	file_orchestrator_service_proto_goTypes = nil
	file_orchestrator_service_proto_depIdxs = nil
}
